source: "Epicurious"
recipes:

- name: Foxhunt
  author: Kyle Davidson
  notes: |+2
      Kirk Estopinal and I took the Pimm's No. 1 cup down to its bones with just Pimm's No. 1, lemon, and sugar, and then juiced it back up with gin for some spine, plus Cynar for depth and finish. Peychaud's and Pimm's No. 1 proved to be so good together, it was like they were separated at birth. With a little bit of a deeper, bitter edge to it than the Violet Hour's house Pimm's No. 1 Cup, this was still a fairly delicate and mild drink that worked well in seasons other than just summer.
  url: https://www.epicurious.com/recipes/food/views/foxhunt
  glassware: coupe
  ingredients:
  - Cynar, to rinse
  - 1 dash Peychaud's Bitters, plus more
  - ½ oz. simple syrup (1:1)
  - ¾ oz. lemon juice
  - ½ oz. Tanqueray London Dry gin
  - 1½ oz. Pimm's No. 1
  steps:
  - Chill your coupe in the freezer, because if you use the ice-and-water method to chill here, you won't get the right concentration of Cynar in the rinse. 
  - Once it's nice and cold, rinse the glass with the Cynar.
  - Build the drink in a shaker tin, starting with a single dash of Peychaud's, then the simple syrup and lemon juice, culminating with the base spirit of gin and Pimm's No. 1. 
  - As you shake this cocktail (using 5 ice cubes), remember that the base spirit is low-proof, so you want to get this cold quickly but not overdilute it. 
  - Strain the cocktail into the coupe and garnish with a few more drops of Peychaud's.
  tags:
  - shaken
  - citrus