source: "Trick Dog"

recipes:
  - name: Che Fivo
    author: David Nayfield
    year: 2018
    ingredients:
    - 1½ ounces Old Grand-Dad bourbon
    - ½ ounce Aveze
    - ½ ounce Aperol
    - ¾ ounce Fennel Syrup
    - ¾ ounce freshly squeezed lemon juice
    - 10 dashes Blackberry Vinegar
    - 4 dashes Kübler absinthe
    - "Garnish: 1 grapefruit wheel & 1 frond fennel"
    steps: 
    - Shake and double strain into a collins glass. Fill with crushed ice. Garnish with fennel front and grapefruit wheel.
    tags:
    - shaken
    - citrus
    - trick dog