source: "Dead Rabbit Mixology & Mayhem"
recipes:

#
  - name: Eidolon
    author: Gregory Buda
    notes: Initially inspired by the Army & Navy cocktail. This ended up being the template for many drinks to come.
    glassware: 
    glassware: 
    ingredients:
    - 1 Egg white
    - 2 DASHES Mace Tincture
    - 2 DASHES House Cardamom Bitters
    - 0.75 OZ Lemon juice
    - 0.5 OZ Orgeat
    - 0.75 OZ Alvear Pale Cream Sherry
    - 0.75 OZ Plantation 3 Stars Rum
    - 0.75 OZ Perry’s Tot Navy Strength Gin
    - "Garnish: lemon twist, discarded"
    steps:
    - Dry shake.
    - Shake with ice.
    - Fine-strain and serve up without ice.
    - Express the lemon twist over the drink and discard.
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - shaken
    - citrus
  - name: Lucky Break
    author: Jillian Vose
    notes: This is a low-ABV negroni variation with a distinctive floral element.
    glassware: 
    ingredients:
    - 1 DASH Peychaud’s Bitters
    - 1 TSP Cinnamon Bark Syrup
    - 0.5 OZ Campari
    - 0.25 OZ Koval Rose Hip Liqueur
    - 0.25 OZ Blume Marillen Apricot Eau-de-Vie
    - 0.5 OZ Plymouth Gin
    - 1 OZ Lillet Rosé
    - 1.5 OZ Martini & Rossi Bianca Vermouth
    - "Garnish: grapefruit twist, discarded"
    steps:
    - Stir with ice.
    - Strain with a julep strainer and serve up without ice.
    - Express the grapefruit peel's oil over the glass and discard.
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - negroni
    - stirred
    - low-abv
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
  - name: 
    author: 
    notes: 
    glassware: 
    ingredients:
    - 
    steps:
    - 
    tags:
    - the dead rabbit
    - the dead rabbit mixology & mayhem
    - 
