source: "The Dead Rabbit"
recipes:

  - name: Split Second
    notes: 
    glassware: 
    ingredients: 
    - 1 oz Plantation Pineapple Stiggins Fancy Rum
    - ¾ oz Jameson Original Irish Whiskey
    - ¼ oz Yellow Chartreuse
    - ¼ oz Giffard Crème de Cacao
    - ¼ oz rich cane sugar syrup
    - 1 dash Angostura bitters
    steps:
    - Combine all ingredients in a mixing glass over ice.
    - Stir until chilled.
    - Strain into a double rocks glass over 1 large ice cube.
    - No garnish.
    tags:
    - stirred
    - old-fashioned
    - the dead rabbit 
