source: "Cocktail Virgin Slut"
recipes:

#
  - name: Cabb
    author: Sother Teague
    url: https://cocktailvirgin.blogspot.com/2021/08/cabb.html
    notes: |+2
      
    glassware: nick & nora
    ingredients:
    - 1 oz Apple Brandy (Morin Calvados)
    - 1 oz Cynar
    - 1/2 oz Dolin Blanc vermouth
    - 1/4 oz Branca Menta
    steps:
    - Build without ice, give a quick stir, and serve at room temperature.
    tags:
    - amor y amargo
    - stirred
    - room temperature
  - name: Bitter Spring
    author: Sother Teague
    year: 2015
    url: https://cocktailvirgin.blogspot.com/2020/05/bitter-spring.html
    notes: |+2
      
    glassware: collins
    ingredients:
    - 1 oz Fernet Branca
    - 1 oz Flor de Caña Gold 4 Year Rum
    - 3/4 oz ginger syrup
    - 3/4 oz orgeat
    - 3/4 oz lemon juice
    - "Garnish: Paychaud's bitters"
    steps:
    - Shake with ice, strain into a Collins glass, fill with crushed ice, and top with several heavy dashes of Peychaud's Bitters.
    tags:
    - amor y amargo
    - shaken
    - citrus
  - name: The Improved
    author: Sother Teague
    url: https://cocktailvirgin.blogspot.com/2021/08/the-improved.html
    notes: |+2
      
    glassware: double rocks
    ingredients:
    - 1 1/4 oz Cockspur 12 Rum
    - 1/4 oz Smith & Cross Jamaican Rum
    - 3/4 oz Zucca
    - 3/4 oz Noilly Prat Sweet Vermouth
    - 10 drop Bittermens Tiki Bitters
    steps:
    - Stir with ice, strain into an old fashioned glass with a large ice cube, and garnish with an orange twist.
    tags:
    - amor y amargo
    - stirred
  - name: Trainspotter
    author: Bruce Schultz
    url: https://cocktailvirgin.blogspot.com/2021/08/trainspotter.html
    notes: |+2
      
    glassware: rocks
    ingredients:
    - 1 1/4 oz Laird's Jersey Lightning Apple Brandy
    - 1 oz Ramazzotti Aperitivo Rosato
    - 3/4 oz Pasubio Vino Amaro
    - 2 dash Bittermens Burlesque Bitters
    - "Garnish: orange twist"
    steps:
    - Stir with ice, strain into a rocks glass with ice, and garnish with an orange twist.
    tags:
    - amor y amargo
    - stirred
  - name: Black Rock Chiller
    author: Sother Teague
    url: https://cocktailvirgin.blogspot.com/2016/12/black-rock-chiller.html
    notes: |+2
      
    glassware: rocks
    ingredients:
    - 1 oz reposado tequila
    - 1 oz Branca Menta
    - 1 oz suze
    steps:
    - Build in a rocks glass (punch cup). 
    - Stir without ice and serve as a room temperature cocktail.
    tags:
    - amor y amargo
    - stirred
    - room temperature
  - name: Improved Kingston Negroni
    author: Sother Teague
    url: https://cocktailvirgin.blogspot.com/2020/01/improved-kingston-negroni.html
    notes: |+2
      
    glassware: double rocks
    ingredients:
    - 1 oz Appleton Reserve Rum
    - 1/2 oz Smith & Cross Jamaican Rum
    - 3/4 oz Punt e Mes
    - 3/4 oz Zucca
    - 1 dash Pimento Bitters
    - "Garnish: orange twist"
    steps:
    - Stir with ice, strain into a double old fashioned glass with ice, and garnish with an orange twist.
    tags:
    - amor y amargo
    - stirred
    - negroni
  - name: Casualty
    author: Chris Elford
    years: 2012
    url: https://cocktailvirgin.blogspot.com/2018/04/casualty.html
    notes: |+2
      
    glassware: nick & nora
    ingredients:
    - 1 1/2 oz Famous Grouse Blended Scotch
    - 3/4 oz Amaro Montenegro
    - 3/4 oz Byrrh Grand Quinquina
    - 2 dash Bittermens Mole Bitters
    - "Garnish: orange twist"
    steps:
    - Stir with ice, strain into a cocktail glass, and garnish with an orange twist.
    tags:
    - amor y amargo
    - stirred
  - name: Jackson Ward
    author: Chris Elford
    year: 2012
    url: https://cocktailvirgin.blogspot.com/2022/10/jackson-ward.html
    notes: |+2
      
    glassware: coupe
    ingredients:
    - 2 oz Rittenhouse Bonded Rye
    - 3/4 oz Amaro Nardini
    - 1/4 oz sweet vermouth
    - 3 dash Cocktail Kingdom Wormwood Bitters
    - 1 dash Regan's Orange Bitters
    - "Garnish: lemon twist"
    steps:
    - Stir with ice, strain into a cocktail coupe, and garnish with a lemon twist.
    tags:
    - amor y amargo
  - name: 8 Amaro Sazerac
    author: ayur Subbarao
    url: https://cocktailvirgin.blogspot.com/2020/10/8-amaro-sazerac.html
    year: 2011
    notes: |+2
      
    glassware: rocks
    ingredients:
    - 1/4 oz Averna
    - 1/4 oz Amaro Ramazzotti
    - 1/4 oz Aperol
    - 1/4 oz Amaro Meletti
    - 1/4 oz Campari
    - 1/4 oz Amaro Ciociaro
    - 1/4 oz Amaro Sibilla
    - 1/4 oz Amaro Lazzaroni
    - 4 dash Peychaud's Bitters
    - 1 dash Orange Citrate Bitters
    - Green chartreuse, to rinse
    - "Garnish: lemon twist"
    steps:
    - Stir with ice, strain into a rocks glass pre-rinsed with Green Chartreuse, and garnish with a lemon twist.
    tags:
    - amor y amargo
    - sazerac
    - stirred
  - name: 443 Special
    author: Nicholas Bennett
    url: https://cocktailvirgin.blogspot.com/2023/04/443-special.html
    notes: |+2
      
    glassware: coupe
    ingredients:
    - 1 oz Glenmorangie Scotch
    - 1/2 oz Laphroaig 10 Year Scotch
    - 3/4 oz Yellow Chartreuse
    - 3/4 oz Amaro Ciociaro
    - "Garnish: lemon twist"
    steps:
    - Stir with ice, strain into a coupe glass, and garnish with a lemon twist.
    tags:
    - amor y amargo
    - stirred
  - name: Sother Teague's C.I.A.
    author: Sother Teague
    url: 
    notes: |+2
      
    glassware: rocks
    ingredients:
    - 1 1/2 oz Laird's Bonded Apple Brandy
    - 3/4 oz Punt e Mes
    - 3/4 oz Cynar
    - 1/4 oz Water
    - 2 dash Apple Bitters
    - "Garnish: orange twist"
    steps:
    - Build in a single old fashioned glass, stir briefly, and garnish with an orange twist. 
    - This is a room temperature cocktail without the need for ice or chilling.
    tags:
    - amor y amargo
    - room temperature
  - name: My Old Piano
    author: Sother Teague
    url: https://cocktailvirgin.blogspot.com/2018/05/my-old-piano.html
    notes: |+2
      
    glassware: coupe
    ingredients:
    - 1 1/2 oz Rittenhouse Rye
    - 3/4 oz Carpano Antica Sweet Vermouth
    - 1/2 oz Mezcal
    - 1/4 oz Kümmel
    - 2 dashes Apple Bitters
    steps:
    - Stir with ice and strain into a cocktail coupe.
    tags:
    - amor y amargo
    - stirred
  - name: The Redemption
    author: Avery Glasser
    url: https://cocktailvirgin.blogspot.com/2021/03/the-redemption.html
    notes: |+2
      
    glassware: rocks
    ingredients:
    - 3/4 oz Jagermeister
    - 3/4 oz Averna
    - 3/4 oz Sweet Vermouth
    - 3/4 oz Laird's Bonded Apple Brandy
    - 6 drop Bittermens Burlesque Bitters
    - 12 drop Bittermens Orange Cream Citrate
    steps:
    - Stir with ice, strain into an old fashioned glass with two ice cubes, garnish with 2-3 drops more orange citrate, and add a splash of soda water.
    tags:
    - amor y amargo
    - stirred
  - name: Pumpernickel
    author: Sother Teague
    url: https://cocktailvirgin.blogspot.com/2014/11/pumpernickel.html
    notes: |+2
      
    glassware: rocks
    ingredients:
    - 1 1/2 oz Jim Beam Bourbon
    - 3/4 oz Punt e Mes
    - 3/4 oz Amaro Ramazzotti
    - 2 dash Angostura Bitters
    steps:
    - Stir with ice and strain into a rocks glass.
    tags:
    - amor y amargo
    - stirred
  - name: Cubist
    author: Sother Teague
    url: https://cocktailvirgin.blogspot.com/2021/08/cubist.html
    notes: |+2
      
    glassware: nick & nora
    ingredients:
    - 1 oz Suze
    - 1 oz Dry Vermouth
    - 1/2 oz Aquavit
    - 2 dash Bitter Truth Olive Bitters
    - "Garnish: lemon twist"
    steps:
    - Stir with ice, strain into a cocktail glass, and garnish with lemon oil from a twist (include peel).
    tags:
    - amor y amargo
    - stirred
  - name: Drop the Anchor
    author: Chris Elford
    url: https://cocktailvirgin.blogspot.com/2022/11/drop-anchor.html
    notes: |+2
      
    glassware: novel
    ingredients:
    - 1 1/2 oz Mount Gay Black Barrel Rum
    - 3/4 oz Byrrh Grand Quinquina
    - 1/2 oz Amaro Montenegro
    - 2 dashes Mole Bitters
    - "Garnish: orange twist"
    steps:
    - Stir with ice, strain into a rocks glass with a big cube, and garnish with an orange twist. 
    - Serve from a chilled flask.
    tags:
    - amor y amargo
    - stirred
  - name: Heaven or Las Vegas
    author: 
    url: https://cocktailvirgin.blogspot.com/2020/01/heaven-or-las-vegas.html
    notes: |+2
      
    glassware: rocks
    ingredients:
    - 1 1/2 oz Evan Williams Bourbon
    - 3/4 oz St. Agrestis Infernal Bitter
    - 3/4 oz Byrrh Quinquina
    - 1 dash Ceylon Cinnamon Bitters
    - "Garnish: lemon twist"
    steps:
    - Stir with ice, strain into a single old fashioned with ice, and garnish with a lemon twist.
    tags:
    - amor y amargo
    - stirred
  - name: Precision Timepiece
    author: Sother Teague
    url: https://cocktailvirgin.blogspot.com/2023/05/precision-timepiece.html
    year: 2015
    notes: |+2
      
    glassware: rocks
    ingredients:
    - 1 1/2 oz Jagermeister
    - 3/4 oz Amaro Montenegro
    - 3/4 oz Aperol
    - 2 dash DeGroff's Pimento Bitters
    - "Garnish: orange twist"
    steps:
    - Stir with ice, strain into an old fashioned glass with ice, and garnish with an orange twist.
    tags:
    - amor y amargo
    - stirred
  - name: Parade of the Fairies
    author: Steven
    url: https://cocktailvirgin.blogspot.com/2020/01/parade-of-fairies.html
    notes: |+2
      
    glassware: double rocks
    ingredients:
    - 1 oz Banhez Espadin & Barril Mezcal
    - 1 oz Cocchi Americano
    - 1/4 oz Green Chartreuse
    - 1/4 oz Galliano
    - 1/2 tsp Rosemary Tincture-Bigallet Thyme Liqueur (50:50)
    steps:
    - Stir with ice and strain into a double old fashioned glass pre-rinsed with Mata Hari Absinthe.
    tags:
    - pouring ribbons
    - sazerac
    - stirred
  - name: Waterproof Watch
    author: Sother Teague
    url: https://cocktailvirgin.blogspot.com/2019/10/waterproof-watch.html
    notes: |+2
      
    glassware: rocks
    ingredients:
    - 1 1/2 oz London Dry Gin
    - 3/4 oz Amaro Montenegro
    - 3/4 oz Aperol
    - 2 dash DeGroff's Pimento bitters
    - "Garnish: orange twist"
    steps:
    - Stir with ice, strain into a rocks glass with fresh ice, and garnish with an orange twist.
    tags:
    - amor y amargo
    - stirred
  - name: Agnes & The Merman
    author: Maria Polise
    url: https://cocktailvirgin.blogspot.com/2018/07/agnes-merman.html
    notes: |+2
      
    glassware: nick & nora
    ingredients:
    - 1 1/2 oz Mezcal
    - 3/4 oz Punt e Mes
    - 1/2 oz Pink Grapefruit Juice
    - 1/2 oz Lime Juice
    - 1/4 oz Agave Nectar
    - "Garnish: lime wheel"
    steps:
    - Shake with ice, strain into a cocktail glass, and garnish with a lime wheel.
    tags:
    - shaken
    - citrus
    - the farmer's cabinet
  - name: Doppelganger
    author: 
    year: 2011
    url: https://cocktailvirgin.blogspot.com/2018/07/doppelganger.html
    notes: |+2
      
    glassware: nick & nora
    ingredients:
    - 3/4 oz Genever
    - 3/4 oz Rhum Agricole
    - 1/2 oz Pineapple Juice
    - 1/2 oz Lime Juice
    - 1/4 oz Green Chartreuse
    - 1/2 oz Simple Syrup
    - "Garnish: mint sprig"
    steps:
    - Shake with ice, strain into a cocktail glass, and garnish with a mint sprig.
    tags:
    - shaken
    - vandaag
  - name: Planet Earth
    author: Joe Donahue
    url: https://cocktailvirgin.blogspot.com/2018/07/planet-earth.html
    notes: |+2
      
    glassware: double rocks
    ingredients:
    - 1 1/2 oz Laird's Straight Apple Brandy
    - 3/4 oz Cynar
    - 1 oz Lime Juice
    - 3/4 oz Orgeat
    steps:
    - Whip shake with a few ice cubes, strain into a double old fashioned glass, fill with ice, and add an eco-friendly straw.
    tags:
    - shaken
    - citrus
    - autumn
    - holiday cocktail lounge
  - name: Passion Grove Swizzle
    author: Matt Pietrek
    url: https://cocktailvirgin.blogspot.com/2018/06/passion-grove-swizzle.html
    notes: |+2
      
    glassware: collins
    ingredients:
    - 1 1/4 oz Plantation 3 Star Rum
    - 3/4 oz Jamaican Overproof Rum
    - 1 oz Pineapple Juice
    - 3/4 oz Lemon Juice
    - 1/2 oz Passion Fruit Syrup
    - 1/2 oz Falernum with strong ginger notes
    steps:
    - Building a Collins glass (I strained out the muddled ginger), fill with crushed ice, and swizzle to mix and chill. Top with crushed ice and garnish festively (mint sprigs).
    tags:
    - swizzle
    - citrus
  - name: Wildflower
    author: Richard Boccato
    url: https://cocktailvirgin.blogspot.com/2018/06/wildflower.html
    notes: |+2
      
    glassware: nick & nora
    ingredients:
    - 1 oz Aged Rhum Agricole (Depaz)
    - 1 oz Cognac (Camus VS)
    - 1 oz Lime Juice
    - 1/2 oz Maple Syrup
    - 1 Orange Wedge
    - "Garnish: cinnamon"
    steps:
    - Shake with ice, strain into a cocktail coupe, and garnish with a pinch of cinnamon (freshly grated cinnamon).
    tags:
    - shaken
    - citrus
    - daiquiri
  - name: Tropical Champagne
    author: Charles Schumann
    year: 1980
    url: https://cocktailvirgin.blogspot.com/2018/06/tropical-champagne.html
    notes: |+2
      
    glassware: flute
    ingredients:
    - 1 oz Dark Rum
    - 1 oz Orange Juice
    - 1/2 oz Lemon Juice
    - 1/2 oz Passion Fruit Syrup
    - Champagne
    steps:
    - Shake with ice, strain into a Champagne flute, and fill with Champagne (~2 oz Willm Blanc de Blancs). I added an orange twist.
    tags:
    - shaken
    - citrus
    - sparkling
  - name: Who Dares Win
    author: Mike Aikman
    url: https://cocktailvirgin.blogspot.com/2018/05/who-dares-win.html
    notes: |+2
      
    glassware: nick & nora
    ingredients:
    - 2 oz Beefeater Gin
    - 3/4 oz Lemon Juice
    - 1/2 oz Orgeat
    - 1/4 oz Kümmel
    - "Garnish: star anise pod"
    steps:
    - Shake with ice, strain into a cocktail glass, and garnish with a star anise pod.
    tags:
    - shaken
    - citrus
  - name: Langosta
    author: Dan Braganca
    year: 2015
    url: https://cocktailvirgin.blogspot.com/2018/05/langosta.html
    notes: |+2
      
    glassware: coupe
    ingredients:
    - 1 oz Mezcal
    - 1/2 oz Lime Juice
    - 1/2 oz Pineapple Juice
    - 1/2 oz Carpano Antica
    - 1/4 oz Crème de Cacao
    - 1 barspoon Campari
    - 1 barspoon Grenadine
    - "Garnish:  orange twist"
    steps:
    - Shake with ice, strain into a cocktail coupe, and garnish with an orange twist.
    tags:
    - backbar
    - shaken
    - citrus
  - name: Desk Job
    author: Donny Clutterbuck
    url:
    notes: |+2
      
    glassware: rocks
    ingredients:
    - 3/4 oz Zacapa 23 Rum
    - 3/4 oz Smith & Cross Rum
    - 3/4 oz Punt e Mes
    - 3/4 oz Cynar
    - "Garnish: lime twist"
    steps:
    - Stir with ice, strain into a rocks glass with ice, and garnish with a lime twist.
    tags:
    - the cure
    - stirred
  - name: 100 Year Old Cigar
    author: Maks Pazuniak
    url: https://cocktailvirgin.blogspot.com/2017/05/100-year-old-cigar.html
    notes: |+2
      
    glassware: coupe
    ingredients:
    - 1 3/4 oz Zacapa 23 Rum (Plantation Dark)
    - 1/2 oz Cynar
    - 1/2 oz Benedictine
    - 1/4 oz Laphroaig 10 Year Scotch
    - 1 dash Angostura Bitters
    - Pernod absinthe
    steps:
    - Stir with ice and strain into an absinthe-rinsed (Pernod) coupe glass.
    tags:
    - sazerac
    - stirred
  - name: Dahlia's Revenge
    author: 
    url: https://cocktailvirgin.blogspot.com/2023/01/dahlias-revenge.html
    notes: |+2
      
    glassware: coupe
    ingredients:
    - 2 oz Mezcal (Fidencio)
    - 3/4 oz Lemon Juice
    - 3/4 oz Honey Syrup
    - "Garnish: cayenne powder"
    steps:
    - Shake with ice, strain into a cocktail coupe, and garnish with a light dusting of cayenne chili powder.
    tags:
    - shaken
    - citrus
  - name: Red Grasshopper
    author: 
    url: https://cocktailvirgin.blogspot.com/2020/10/red-grasshopper.html
    notes: |+2
      
    glassware: coupe
    ingredients:
    - 2 oz Blanco Tequila (Lunazul)
    - 3/4 oz Lime Juice
    - 3/4 oz Honey Syrup
    - "Garnish: cayenne chili powder"
    steps:
    - Shake with ice, strain into a cocktail coupe, and garnish with a light dusting of cayenne chili powder.
    tags:
    - shaken
    - citrus
    - margarita
  - name: Yvonne's Honey Bee
    author: Sean Frederick
    url: https://cocktailvirgin.blogspot.com/2016/04/yvonnes-honey-bee.html
    notes: |+2
      
    glassware: coupe
    ingredients:
    - 2 oz Plantation Barbados 5 Year Rum
    - 1/4 oz St. George Pear Eau de Vie
    - 3/4 oz Honey Syrup (1:1)
    - 3/4 oz Lemon Juice
    - 1 Egg White
    - "Garnish: 10 drops of Angostura bitters"
    steps:
    - Shake once without ice and once with ice, strain into a coupe, and garnish with 10 drops of Angostura bitters.
    tags:
    - shaken
    - citrus
  - name: Precursor
    author: 
    year: 2015
    url: https://cocktailvirgin.blogspot.com/2024/01/precursor.html
    notes: |+2
      
    glassware: coupe
    ingredients:
    - 1 oz Bols Barrel-Aged Genever
    - 1 oz Ransom Old Tom Gin
    - 1 oz Cocchi Sweet Vermouth
    - 1/4 oz Luxardo Maraschino
    - 2 dash orange bitters
    - "Garnish: orange twist"
    steps:
    - Stir with ice.
    - Strain into a cocktail coupe. 
    - Garnish with an orange twist.
    tags:
    - stirred