source: "The New York Times"
recipes:

  - name: Bitter Coffee
    author: Maksym Pazuniak
    glassware: 
    ingredients:
    - 1½ ounces Cynar
    - ½ ounce dark rum
    - ½ ounce grade B maple syrup
    - 1 egg yolk
    - 5 drops vanilla extract
    - 3 ounces hot, strong coffee
    - 1 nutmeg
    steps: 
    - Fill a small saucepan halfway with water. Over medium heat, bring to a gentle boil.
    - In a heat-safe bowl about the same diameter as the saucepan, whisk together the Cynar, rum, maple syrup, egg yolk and vanilla. Place bowl on top of the saucepan, as water continues boiling, and whisk mixture for about another 2 to 3 minutes, just long enough to warm it and thicken it slightly.
    - Pour mixture into an Irish coffee mug and top with the coffee while stirring. Grate whole nutmeg or sprinkle ground nutmeg over top.
    tags:
    - stirred
    - heated
    - caffeinated
    - cure