source: "Miscellaneous"
recipes:

#
- name: Chas
  author: Murray Stenson
  url: https://cocktailpartyapp.com/drinks/chas/
  notes: |+2
    "One of the regulars at the Zig Zag Cafe loved his bourbon cocktails, to the point of never having anything else. There are, of course, only so many bourbon cocktail recipes out there, so one time he asked Murray to come up with something different, and this was the result. The customers name was Charles, or 'Chaz' to his friends."
  glassware: coupe
  ingredients:
  - 2½ ounces Bourbon
  - ¼ ounce Amaretto or Crème de noyaux
  - ¼ ounce Bénédictine
  - ¼ ounce Cointreau
  - ¼ ounce Grand Marnier
  steps:
  - Combine all ingredients with ice in a mixing glass and stir.
  - Strain into a coupe glass.
  - No garnish.
  tags:
  - stirred
  - zig zag zig
- name: The Weeper's Joy
  author: 
  url: https://cocktailvirgin.blogspot.com/2019/02/the-weepers-joy.html
  notes: |+2
    
  glassware: nick & nora
  ingredients:
  - 1/4 ounce simple syrup
  - 3/4 ounce Kübler Absinthe
  - 3/4 ounce Cocchi Storico Vermouth di Torino
  - 3/4 ounce Kümmel
  - 1/4 ounce Pierre Ferrand Dry Curacao
  steps:
  - Combine all ingredients with ice in a mixing glass and stir.
  - Strain into a coupe glass.
  - No garnish.
  tags:
  - stirred