source: "The Maison Premiere Almanac: Cocktails, Oysters, Absinthe, and Other Essential Nutrients for the Sensualist, Aesthete, and Flaneur"
hidden: true
recipes:

#Carondelet
  - name: Carondelet Syrup
    notes: |+2
      
    ingredients: 
    - 1 cup water
    - 1 cup orange blossom honey
    - 5 pinches of Maldon salt  
    - 2 dashes of orange flower water
    - 2 dashes of Madagascar vanilla extract
    steps:
    - In a small saucepan over medium-high heat, bring the water to a low simmer. Add the honey and stir until the honey and water are combined. Then add the salt, orange flower water, and vanilla extract and stir until dissolved. Allow the mixture to cool before using.

#Maison Bloody Mary
  - name: Maison Bloody Mary Mix
    notes: |+2
      Makes enough for 10 Bloody Marys.
    ingredients: 
    - 3 celery stalks			
    - 1 white onion, peeled
    - 1 large carrot, peeled
    - 3 garlic cloves
    - 36 ounces tomato juice
    - 6 canned chipotle peppers
    - 1 cup prepared horseradish
    - 1 cup Dijon mustard
    - 8 ounces Worcestershire sauce
    - 1 tablespoon salt
    - ½ tablespoon black pepper
    - 3 ounces Tabasco sauce
    steps:
    - Juice the celery, onion, carrot, and garlic, and combine their liquids with the tomato juice in a large bucket. Blend the chipotle peppers with the horseradish, mustard, and a little of the tomato juice mixture. Add the blended chipotle pepper mixture, Worcestershire sauce, salt, pepper, and Tabasco to the large bucket of vegetable juice, stir well, and refrigerate overnight.

#Here are the recipes for add-ins that take ordinary cocktails to the next level. To ensure stability and preservation, we add an ounce of vodka to our syrups per quart.
  - name: Ginger Syrup (1:1)
    notes: |+2
      
    ingredients: 
    - 1 part ginger juice (see Note)
    - 1 part superfine sugar
    - 2 cinnamon sticks
    steps:
    - In a pot set over medium heat, combine equal parts ginger juice and superfine sugar. Bring the mixture to a low simmer and stir until the sugar has dissolved. Remove the pot from the heat. Add the cinnamon sticks and let sit for 20 minutes. The syrup can be stored in the refrigerator for two weeks.
    - Note • To make ginger juice, take whole, unpeeled ginger and run it through a juice extractor. Skim off any scum. Run once through a fine-mesh strainer to remove any particulate matter.
  - name: Simple Syrup (1:1)
    notes: |+2
      
    ingredients: 
    - 1 part sugar
    - 1 part water
    steps:
    - In a pot, combine the sugar and water in equal parts and stir until the sugar has dissolved, but do not heat the pot. Warm to hot water may be used to help the sugar dissolve. The syrup can be stored in the refrigerator for two weeks.
  - name: Rich Simple Syrup (2:1)
    notes: |+2
      
    ingredients: 
    - 2 parts sugar
    - 1 part water
    steps:
    - In a pot, combine the sugar and water and stir until the sugar has dissolved, but do not heat the pot. Warm to hot water may be used to help the sugar dissolve. The syrup can be stored in the refrigerator for two weeks.
  - name: Raspberry Syrup
    notes: |+2
      
    ingredients: 
    - 6 ounces raspberries
    - 1 cup Rich Simple Syrup
    - 6 drops of rose flower water
    steps:
    - Add the raspberries to the simple syrup. Add the rose flower water and blend until smooth. Strain the mixture through a fine-mesh strainer. The syrup can be stored in the refrigerator for two weeks.
  - name: Demerara Simple Syrup (2:1)
    notes: |+2
      
    ingredients: 
    - 2 parts Demerara sugar
    - 1 part water
    steps:
    - In a pot set over medium heat, combine equal parts Demerara sugar and water. Bring the mixture to a low simmer and stir until the sugar has dissolved. Remove the pot from the heat and allow to cool. The syrup can be stored in the refrigerator for two weeks.
  - name: Gentian Syrup
    notes: |+2
      
    ingredients: 
    - 1 cup sugar
    - 1 cup water
    - 1 grapefruit peel
    - ¼ ounce gentian root
    steps:
    - In a small pot set over medium heat, combine the sugar, water, and grapefruit peel, and stir until the sugar is dissolved.
    - Remove the pot from the heat and add the gentian root. Steep the gentian for ten minutes and then strain the mixture through a fine-mesh strainer. The syrup can be stored in the refrigerator for two weeks.
  - name: Saline Solution
    notes: |+2
      
    ingredients: 
    - 2 parts water
    - 1 part salt
    steps:
    - In a pot or bowl, combine the water and salt. Mix until the salt is dissolved. The solution can be stored in the refrigerator for two weeks.
  - name: Maison Orgeat
    notes: |+2
      Yields about 1½ quarts.
    ingredients: 
    - 8 ounces slivered almonds
    - 1 quart unsweetened almond milk
    - 1 quart sugar
    - 1 teaspoon kosher salt
    steps:
    - Place the nuts on a sheet tray and bake at 350ºF, stirring every couple of minutes until the almonds reach a deep golden brown, approximately 8 minutes. In a large pot set over medium heat, add the almond milk and sugar and heat through. Add the toasted almonds and salt, then simmer the mixture for 45 minutes, stirring occasionally. Strain through a fine-mesh strainer and then cool the liquid rapidly in an ice bath. The orgeat can be stored in the refrigerator for several weeks.
  - name: Maison Coconut Syrup
    notes: |+2
      
    ingredients: 
    - 3 parts coconut syrup (such as Giffard)
    - 1 part coconut milk
    steps:
    - In a pot set over low heat, combine the coconut syrup and coconut milk and stir until well mixed. Allow to cool. The syrup can be stored in the refrigerator for several weeks.
  - name: Maison Toasted Coconut Syrup
    notes: |+2
      Yields just over 1 quart.
    ingredients: 
    - 1 quart coconut milk
    - 2 cups toasted coconut flakes
    - 2 cups sugar
    - 1 tablespoon salt
    - Peels of 3 limes
    - 1 ounce Kalani coconut rum liqueur
    steps:
    - In a large pot over medium heat, combine the coconut milk and flakes, sugar, salt, and lime peels. Simmer for 45 minutes. Strain through a fine-mesh strainer and add the rum liqueur. The syrup can be stored in the refrigerator for three weeks.
  - name: Maison 7-Spice Chai Syrup
    notes: |+2
      Yields about 1½ quarts.
    ingredients: 
    - 2 cups water
    - 2 cups sugar
    - 1½ tablespoons whole cloves
    - 1 star anise
    - 1½ teaspoons ground allspice
    - 1 cinnamon stick
    - 1 tablespoon black pepper
    - ½ cup roughly chopped ginger
    - 1½ teaspoons ground cardamom
    - 1½ teaspoons kosher salt
    - Peel of 2 oranges
    steps:
    - In a medium pot set over medium heat, combine the water, sugar, cloves, star anise, allspice, cinnamon stick, black pepper, ginger, cardamom, salt, and orange peels. Bring to a simmer and cook for 30 minutes. Strain the mixture through a fine-mesh strainer. Express and discard the orange peel while the mixture cools. The syrup can be stored in the refrigerator for two weeks.
  - name: Lime Cordial
    notes: |+2
      
    ingredients: 
    - Zest of 3 limes
    - 1 cup sugar
    - 1 cup lime juice
    - ½ ounce vodka
    steps:
    - In a container with a lid, combine the lime zest and sugar and leave covered at room temperature for 24 hours, or overnight, agitating intermittently. After the marination period, add the lime juice and vodka, and stir until thoroughly mixed and the sugar is dissolved. Strain the liquid through a fine-mesh strainer and chill. The cordial can be stored in the refrigerator for a month.
  - name: Lemon Cordial
    notes: |+2
      
    ingredients: 
    - Zest of 3 lemons
    - 1 cup sugar
    - 1 cup lemon juice
    - ½ ounce vodka
    steps:
    - In a container with a lid, combine the lemon zest and sugar and leave covered at room temperature for 24 hours, or overnight, agitating intermittently. After the marination period, add the lemon juice and vodka to the mixture and stir until thoroughly combined and the sugar is dissolved. Strain the liquid through a fine-mesh strainer and chill. The cordial can be stored in the refrigerator for a month.
  - name: Maison Grenadine
    notes: |+2
      
    ingredients: 
    - 8 ounces pomegranate juice, such as POM Wonderful
    - ½ cup Sugar In The Raw or Demerara sugar
    - 1 ounce pomegranate molasses, such as Al Wadi
    - Peel of 1 orange
    steps:
    - In a small pot set over low heat, combine the pomegranate juice and sugar, and stir until the sugar dissolves. Do not allow the mixture to boil.
    - Remove the pot from the heat and add the pomegranate molasses.
    - Express and then discard the orange peel. Chill and store. The grenadine can be stored in the refrigerator for two weeks.
  - name: Passion Fruit Syrup
    notes: |+2
      
    ingredients: 
    - 1 part passion fruit puree
    - ½ part grenadine
    - ½ part Demerara sugar
    - 2 parts coconut syrup (such as Giffard)
    steps:
    - In a pot set over low heat, combine the passion fruit puree, grenadine, sugar, and coconut syrup, and stir until the sugar is dissolved. Cool and store the mixture. The syrup can be stored in the refrigerator for two weeks.
  - name: Honey Syrup (1:1)
    notes: |+2
      
    ingredients: 
    - 1 part hot water
    - 1 part honey
    steps:
    - In a pot set over low heat, combine equal amounts of hot water and honey. Stir until the honey is dissolved. The syrup can be stored in the refrigerator for a month.
  - name: 
    notes: |+2
      
    ingredients: 
    - 
    steps:
    - 
