source: "Cure: New Orleans Drinks and How to Mix 'Em"
hidden: true

recipes:
  - name: Pickled Mirliton
    notes: Makes 1 pint (480 mL).
    ingredients: 
    - 1 mirliton (chayote), about 8 ounces (225 g)
    - ¾ cup (180 ml) white vinegar
    - ¾ cup (180 ml) white sugar
    - 1 tablespoon kosher salt
    steps:
    - Cut the mirliton in half and scrape away the seeds. Cut the flesh into ⅛-inch-wide (3-mm) French fry shapes and soak in ice water while you prepare the brine.In a small saucepan, combine the vinegar, sugar, salt, and 1 cup (240 ml) water and bring to a boil over high heat. At the first crack of a boil, remove the pan from the heat. Place the mirliton in a heatproof nonreactive pint-size (480-ml) container and pour the brine over the top. Make sure the mirliton is fully submerged (add water to top if necessary). Refrigerate for at least 1 hour before using or up to 1 week.
  - name: Salted Pistachio Tincture
    notes: Makes ½ cup (120 mL).
    ingredients: 
    - ½ cup (65 g) salted shelled pistachios
    - ½ cup (120 ml) vodka, or as needed
    steps:
    - In a small nonreactive container, combine the pistachios and enough vodka to barely cover the pistachios. Cover the container and let sit at room temperature for 48 hours. Strain the mixture and store the vodka in a nonreactive container for up to 6 months.
  - name: Sage Syrup
    notes: Makes 1 cup (240 mL).
    ingredients: 
    - 10 fresh sage leaves
    - 1 cup (200 g) sugar
    - 1 cup very hot water
    steps:
    - Muddle the sage leaves in the tin of a cocktail shaker, then pour 1 cup (240 ml) very hot water over the top. Let sit for 8 minutes, until the water is infused with the sage. Strain out the sage leaves, add the sugar, and stir until dissolved. Store airtight in the fridge for up to 2 weeks.
  - name: Hurricane Syrup
    notes: Makes about 1 cup (240 mL).
    ingredients: 
    - ½ cup (120 ml) passion fruit puree
    - 1 cup (200 g) white sugar
    - 1 tablespoon (15 ml) pomegranate molasses
    - 1 tablespoon (15 ml) Goya guava jelly, cut into small pieces
    - ¼ ounce (7 g) dried hibiscus flowers
    steps:
    - In a small saucepan, combine the passion fruit puree and 1 cup (240 ml) water and heat over medium heat until gently steaming. Add the sugar and pomegranate molasses and stir until dissolved. Add the guava jelly and stir until dissolved. Remove the saucepan from the heat and stir in the hibiscus flowers. Let cool to room temperature, strain out the hibiscus flowers, and decant into a nonreactive container. Store airtight in the refrigerator for up to 1 month.
  - name: Banana Syrup
    notes: Makes 2 cups (480 mL).
    ingredients: 
    - 1 very ripe banana, peeled and chopped
    - 2 cups (480 ml) Simple Syrup
    steps:
    - In a nonreactive container, combine the chopped banana and one-half of the peel with the simple syrup. Infuse at room temperature for 24 hours, then fine-strain into another nonreactive container. Refrigerate for up to 1 week.
  - name: Pepita Orgeat
    notes: Makes about 1½ cups (360 mL).
    ingredients: 
    - 4 ounces (115 g) hulled pumpkin seeds
    - 1½ cups (360 ml) water
    - 1½ cups (360 ml) white sugar, or as needed
    steps:
    - Preheat the oven to 350°F (175°C) and line a baking sheet with parchment paper. Spread the pumpkin seeds on the parchment paper and roast until very lightly toasted, 5 to 7 minutes.
    - Soak the toasted pumpkin seeds in the water for at least 3 hours or up to 24 hours. Transfer the seeds and water to a blender and blend until pureed. Strain through a fine-mesh sieve into a nonreactive container (discard the solids), then add an equal measure by volume of sugar and stir until dissolved. Store airtight in the refrigerator for up to 1 week.
  - name: Chamomile Simple Syrup
    notes: 
    ingredients: 
    - 1 part white sugar
    - 1 part freshly brewed chamomile tea
    steps:
    - Combine the sugar and tea in a saucepan and bring to a simmer over medium-high heat. As soon as the sugar is dissolved, remove from the heat and allow to cool. Transfer to a nonreactive container and store airtight in the fridge for up to 2 weeks.
  - name: Fennel Syrup
    notes: Makes 2 cups (480 mL).
    ingredients: 
    - 2 tablespoons fennel seeds
    - 2 cups (480 ml) hot (190 to 200°F/88 to 93°C) water
    - 2 cups (400 g) white sugar
    steps:
    - In a small skillet over medium heat, toast the fennel seeds until fragrant, 1 to 2 minutes. Transfer to a bowl, add the water, and infuse until the water is cool. Add the sugar, stir until dissolved, then fine-strain and store in the refrigerator for up to 4 weeks.
  - name: Pineapple Syrup
    notes: 
    ingredients: 
    - 1 part fresh pineapple juice
    - 1 part white sugar
    steps:
    - Combine the pineapple juice and sugar in a small saucepan and bring to a boil. At the first crack of a boil, remove from the heat and continue stirring until dissolved. Allow to cool, then transfer to a nonreactive container. Store airtight in the refrigerator for up to 2 weeks.
  - name: Cantaloupe Syrup
    notes: Makes about 1½ cups (360 mL).
    ingredients: 
    - ½ cantaloupe (about 1½ pounds / 680 g), peeled, cored, and cut into cubes
    - White sugar
    steps:
    - In a blender, puree the cantaloupe until smooth, then fine-strain. Combine the strained juice with an equal part of white sugar in the blender, then blend on medium speed for about 5 minutes. Store airtight in the refrigerator for up to 3 days.
  - name: Raspberry Shrub
    notes: Makes about 2½ cups (600 mL).
    ingredients: 
    - 1 cup (125 g) fresh raspberries
    - 1 cup (240 ml) cold water
    - 1 cup (200 g) white sugar
    - 1 cup (240 ml) white vinegar
    steps:
    - Combine all the ingredients in the bowl of a food processor or blender and puree. Strain through a fine-mesh sieve into a nonreactive container. Store airtight in the refrigerator for up to 3 months.
  - name: Tabasco Shrub
    notes: 
    ingredients:
    - 2 parts Demerara Syrup
    - 1 part Tabasco hot sauce
    - 1 part water
    steps:
    - Combine the ingredients in a saucepan and bring to a simmer over medium-high heat. Cook for 10 minutes, then remove from the heat and transfer to a nonreactive container. Store airtight in the refrigerator for up to 4 weeks.
  - name: Agave Syrup
    notes: 
    ingredients: 
    - 2 parts raw agave nectar
    - 1 part boiling water
    steps:
    - Combine in a nonreactive container and stir until dissolved. Store airtight in the refrigerator for up to 4 weeks.
  - name: Black Pepper Syrup
    notes: Makes about 1 cup (240 mL).
    ingredients: 
    - 1 cup (200 g) white sugar
    - 1 cup (240 ml) water
    - ¼ cup (24 g) freshly ground black pepper
    steps:
    - Combine all the ingredients in a small saucepan and bring to a boil. Reduce heat to a simmer and cook for 5 minutes. Double-strain, multiple times if needed, until there are no particles left and the syrup is clear. Transfer to a nonreactive container. Store airtight in the refrigerator for up to 4 weeks.
  - name: Cinnamon Syrup
    notes: Makes about 1 cup (240 mL).
    ingredients: 
    - 1 cup (240 ml) water
    - 3 cinnamon sticks
    - 1 cup (200 g) white sugar
    steps:
    - Combine the water and cinnamon in a small saucepan and bring to a boil. Cover, reduce the heat to a simmer, and cook for 20 minutes. Add the sugar and stir until dissolved. Remove from heat, let sit for at least 1 hour and up to 4 hours, then strain into a nonreactive container. Store airtight in the refrigerator for up to 4 weeks.
  - name: Demerara Syrup
    notes: 
    ingredients: 
    - 2 parts Demerara sugar
    - 1 part water
    steps:
    - Combine the sugar and water in a small saucepan and bring to a boil. At the first crack of a boil, remove from the heat and continue stirring until dissolved. Let cool then transfer to a nonreactive container. Store airtight in the refrigerator for up to 4 weeks.
  - name: Ginger Syrup
    notes: 
    ingredients: 
    - 1 part fresh ginger juice
    - 1 part white sugar
    steps:
    - Combine the ginger juice and sugar in a blender. Blend until smooth and combined, then fine-strain into a nonreactive container. Store airtight in the refrigerator for up to 2 weeks.
  - name: Grenadine
    notes: Makes about 1 quart (1 liter).
    ingredients: 
    - 2½ cups (600 ml) pomegranate juice
    - 1½ cups (360 ml) Simple Syrup
    - ½ cup (120 ml) brandy
    - 14 drops orange flower water
    steps:
    - Combine the pomegranate juice and 1 cup (120 ml) of the simple syrup in a medium saucepan and bring to a boil. Cook until reduced by ½ cup (120 ml), then remove from the heat and stir in the brandy, orange flower water, and remaining ½ cup (120 ml) simple syrup. Let cool then transfer to a nonreactive container and store airtight in the refrigerator for up to 2 weeks.
  - name: Honey Syrup
    notes: 
    ingredients: 
    - 2 parts Honey
    - 1 part boiling water
    steps:
    - Combine in a nonreactive container and stir until dissolved. Store airtight in the refrigerator for up to 4 weeks.
  - name: Lemon-Orange Oleo Syrup
    notes: Makes about 1 cup (240 mL).
    ingredients: 
    - Peels of 2 lemons
    - Peel of 1 orange
    - 1 cup (200 g) white sugar
    - 1 cup (240 ml) hot water
    steps:
    - Combine the peels and sugar in a nonreactive container and let rest in a warm, dark place for at least 8 hours and up to 48 hours. Add the hot water and stir until the sugar dissolves. Once cool, fine-strain into a nonreactive container. Store airtight in the refrigerator for up to 4 weeks.
  - name: Orgeat
    notes: 
    ingredients: 
    - 2 cups (280 g) raw almonds
    - 1 part unsweetened almond milk
    - 1 part white sugar
    - 1 part Demerara sugar
    - Rosewater, to taste
    - Orange flower water, to taste
    steps:
    - Preheat the oven to 350°F (165°C). Spread the almonds in an even layer on a baking sheet and toast, shaking the pan once during cooking, 8 to 12 minutes, or until fragrant.
    - Meanwhile, combine the almond milk and sugars in a medium saucepan and bring to a low simmer over medium heat. Stir until the sugars have dissolved, then remove from the heat. Add the toasted almonds and allow to cool to room temperature, then add rosewater and orange flower water to taste. Strain into a nonreactive container and store airtight in the fridge for up to 2 weeks.
  - name: Saline Solution
    notes: 
    ingredients: 
    - 1 part Maldon sea salt
    - 2 parts water
    steps:
    - Combine the salt and water in a saucepan and bring to a simmer over medium-high heat. Once the salt is dissolved, remove from the heat and allow to cool. Transfer to a nonreactive container and store airtight in the fridge for up to 4 weeks.
  - name: Simple Syrup
    notes: 
    ingredients: 
    - 1 part white sugar
    - 1 part cold water
    steps:
    - Combine in a blender and puree until the sugar is dissolved, or combine in a nonreactive lidded jar and shake until the sugar is dissolved. Store airtight in the refrigerator for up to 4 weeks.