source: 
hidden: true
recipes:

#Benton's Old-Fashioned
  - name: Benton’s Bacon Fat-Washed Four Roses Bourbon
    notes: 
    ingredients: 
    - 1½ ounces (by volume) bacon fat rendered from Benton’s Country Bacon
    - 750 ml bottle Four Roses bourbon
    steps:
    - Warm the bacon fat in a small saucepan over low heat, stirring until it is melted, about 5 minutes. Combine the melted fat with the bourbon in a large freezer-safe container and stir. Cover and let sit at room temperature for 4 hours, then place the container in the freezer for 2 hours. Remove the solid fat from the surface of the bourbon and discard. Strain the bourbon through a terry cloth towel or a double layer of cheesecloth into a bottle and store in the refrigerator for up to 2 months.

#Earl Grey Marteani
  - name: Earl Grey Tea-Infused Tanqueray London Dry gin
    notes: 
    ingredients: 
    - 1 cup Tanqueray London Dry gin
    - 1 tablespoon loose Earl Grey tea leaves
    steps:
    - Combine the ingredients in a bottle. Stir briefly and gently. Infuse for 2 hours. Fine strain the tea leaves from the gin. The infusion will keep at room temperature for 2 days.

#Gin-Gin Mule 
  - name: Homemade Ginger Beer
    notes: 
    ingredients: 
    - 1 quart filtered water
    - 4 ounces finely chopped fresh ginger
    - 1 ounce light brown sugar
    - ½ ounce lime juice
    steps:
    - Add the water to a pot and bring to a boil. Put the ginger root in a food processor. Add 1 cup of the boiling water to the ginger to make processing easier. Process until coarsely ground. Return the ginger to the remaining boiling water and turn off the heat. Stir well, then cover and let sit for 1 hour. Strain through a fine chinois or cheesecloth, pressing down firmly on the ginger to extract the most flavor. Add the brown sugar and lime juice. Let cool. Transfer to glass bottles and store in the refrigerator. Ginger beer will keep for 2 weeks.

#Mezcal Mule
  - name: Ginger Wort
    notes: Makes 25 ounces.
    ingredients: 
    - 3 cups (24 ounces) water
    - 1 cup (8 ounces) minced fresh ginger
    - 1½ ounces light brown sugar
    - ¾ ounce lime juice
    steps:
    - Boil the water, then add it to the minced ginger and brown sugar in a nonreactive container. Cover for 90 minutes, then strain through a chinois, pressing the ginger to extract as much liquid as possible. Add the lime juice, bottle, and refrigerate.

#Mr. Brown
#Porn Star Martini
  - name: Vanilla Syrup
    notes: 
    ingredients: 
    - 8 ounces sugar
    - 8 ounces water
    - 1 vanilla bean
    steps:
    - Combine the sugar and water in a small saucepan. Slice the vanilla bean down the center, scraping out the insides, and add everything directly to the sugar-water mixture. Stir over medium-high heat until it comes to a boil and the sugar has dissolved completely. Remove from the heat and let cool. Taste. If the desired flavor is reached, remove the vanilla bean. If a stronger flavor is needed, leave the solids in the syrup. Pour into a container, cover, and refrigerate. Keeps for 2 weeks.

#Penicillin
  - name: Ginger Honey Syrup
    notes: 
    ingredients: 
    - 1 cup honey
    - 6-inch knob of fresh ginger, peeled and sliced
    - 1 cup water
    steps:
    - In a small pot, combine the honey, ginger, and water and bring to a boil. Reduce the heat and simmer for 5 minutes. Refrigerate overnight, then strain, discarding the solids.