source: "PUNCH"
hidden: true
recipes:
  - name: Cardamom-Coriander Syrup
    ingredients:
      - 2 cinnamon sticks, broken up
      - 1 1/2 teaspoons coriander seeds
      - 1 tablespoon black cardamom pods
      - 1/4 teaspoon red pepper flakes
      - 4 ounces high-proof rum
      - 15 ounces hot water
      - 3/4 cup fine granulated sugar
    steps:
      - Preheat the oven to 450°F. 
      - Spread the cinnamon sticks, coriander seeds, and cardamom on a rimmed baking sheet and toast in the oven, tossing occasionally to prevent burning, until fragrant but not burned, about 8 minutes.
      - Combine the toasted spices, red pepper flakes, and rum in a blender, and blend on high speed until evenly ground, about 2 minutes.
      - Meanwhile, in a separate container, combine the hot water and sugar, and stir until the sugar is completely dissolved.
      - Set aside.
      - Using a coffee filter or multiple layers of cheesecloth, strain the spice and rum mixture into the sugar syrup.
      - Stir to combine.
      - Transfer to a clean, sealable bottle or container.
      - This syrup will keep, refrigerated, for 2 months.
      - Shake thoroughly before using.
      - As a substitute for the cardamom-coriander syrup, Volk recommends using 1/4 ounce St. Elizabeth Allspice Dram and 1 teaspoon of rich simple syrup (2:1, sugar:water).