source: "Spirits of Latin America"
hidden: true
recipes:

#
  - name: Raspberry Syrup
    notes: Makes 1 quart.
    ingredients: 
    - 1 cup raspberries
    - 2 cups granulated sugar
    - 1 cup water
    steps:
    -  Place the ingredients in a blender and blend on high speed until the contents are well integrated. 
    - Pour through a chinois strainer to remove solids and transfer to an airtight container. 
    - Store in the refrigerator for up to 2 weeks.
  - name: Eucalyptus Tincture
    notes: Makes 20 ounces.
    ingredients: 
    - 2 oz (by weight) eucalyptus leaves, washed
    - 9 oz Spirytus Rektyfikowany or other everclear alcohol 
    - 9 oz water
    steps:
    -  Combine the eucalyptus and alcohol in a quart-size container. 
    - Let sit covered in open air for 36 hours. 
    - Strain, add the water, and bottle. 
    - Store in the refrigerator indefinitely.
  - name: Rhubarb Syrup
    notes: Makes 1 cup. 
    ingredients: 
    - ½ lb rhubarb cut into 1-inch cubes
    - ½ lb cleaned and hulled strawberries
    - Zest and juice of 1 small orange (yields ½ cup orange juice)
    - Zest of 1 lemon
    - 1 cup superfine sugar
    - 1 Tbsp vanilla extract
    steps:
    - Mix all the ingredients together in a saucepan and simmer over low heat for 20 minutes. 
    - Remove from the heat and allow to cool. 
    - Blend with an immersion blender and then transfer to an airtight container. 
    - Store in the refrigerator for up to 4 weeks.
  - name: Watermelon Syrup
    notes: Makes 2 cups.
    ingredients: 
    - 2 cups cubed seedless watermelon
    - ¾ cup superfine sugar
    steps:
    - Blend the watermelon in a blender to yield about 12 ounces of juice. 
    - Add the sugar and blend again until fully dissolved. 
    - Transfer to an airtight container. 
    - Store in the refrigerator for up to 2 weeks.
  - name: Fig-Infused Rancho Tepua Bacanora Blanco
    notes: Makes 750 mL.
    ingredients: 
    - 5 medim figs
    - 750 ml Rancho Tepua Bacanora Blanco
    steps:
    - Slice the figs and place in a small pan over medium heat until browned, 5 to 8 minutes, and let cool slightly. 
    - Muddle the figs in a food-safe container and add the Bacanora. 
    - Let sit for 8 hours, stirring occasionally. 
    - Pour through a chinois strainer to remove solids and bottle. 
    - Store in the refrigerator indefinitely.
  - name: Serrano Syrup
    notes: Makes 8 ounces.
    ingredients: 
    - 4 serrano peppers (preferably red or orange)
    - 2 oz water
    - 4 oz agave nectar
    steps:
    - Using a juicer, juice the serranos to yield approximately 2 oz. 
    - Be sure to wear gloves for cutting and wash knives and surfaces immediately. 
    - Add the water and nectar to the serrano juice. Stir to integrate, then fine-strain and bottle. 
    - Store in the refrigerator for up to 2 weeks.
  - name: Mole Negro Kahlua
    notes: Makes 1 quart.
    ingredients: 
    - 5 oz mole negro paste
    - 750 ml Kahlua Coffee Liqueur
    steps:
    - Combine the mole negro and Kahlua in a blender and blend until unified. 
    - Transfer to an airtight container. 
    - Store in the refrigerator indefinitely.
  - name: Tumericane
    notes: Makes 2 cups.
    ingredients: 
    - 2 tsp powdered turmeric
    - 1 cup water
    - 2 cups cane sugar
    steps:
    - Add the turmeric to the water and bring to a boil over high heat. 
    - Then add the sugar and turn the heat to medium, stirring until the sugar dissolves. 
    - Remove from the heat, allow to cool, and bottle. 
    - Store in the refrigerator for up 1 month.
  - name: Mace-Infused Tapatio 110 Tequila Blanco
    notes: Makes 10 ounces.
    ingredients: 
    - 10 oz Tapatio 110 Tequila Blanco
    - 1 tbsp dried and ground mace
    steps:
    - Combine the Tapatio and mace in a quart-size jar and let rest for 3 days unrefrigerated. 
    - Strain through a chinois and bottle. 
    - Store refrigerated indefinitely.
  - name: Passion Fruit Syrup
    notes: Makes 4 ounces.
    ingredients: 
    - 3 oz Perfect Purée passion fruit puree
    - 1 oz superfine sugar
    steps:
    - Combine the ingredients in a blender, blend until dissolved and integrated, and bottle. 
    - Store in the refrigerator for up to 1 month.
  - name: Guava Syrup
    notes: Makes 7 ounces.
    ingredients: 
    - 4 oz Perfect Purée pink guava puree
    - 4 oz superfine sugar
    steps:
    - Combine the ingredients in a blender. 
    - Blend until dissolved and integrated. 
    - Transfer to an airtight container. 
    - Store in the refrigerator for up to 1 month.
  - name: Donn's Mix
    notes: Makes 3 ounces.
    ingredients: 
    - 2 oz grapefruit juice
    - 1 oz Cinnamon Bark Syrup
    steps:
    - Combine the ingredients in a glass and stir to fully incorporate. 
    - Store in the refrigerator for up to 4 days.
  - name: Spicy Salt
    notes: Yields 4 tablespoons.
    ingredients: 
    - 2 Tbsp superfine sugar
    - 1 Tbsp ground pink peppercorns
    - 1 Tbsp salt
    steps:
    - Add the sugar, pink peppercorns, and salt to a bowl and stir to integrate. 
    - Store in an airtight jar in a cool dry place indefinitely.
  - name: Poblano Syrup
    notes: Makes 3 cups.
    ingredients: 
    - 8 poblano peppers, stemmed but not seeded
    - 1 cup agave nectar
    steps:
    - Using a juice extractor, juice the poblanos to yield about 2 cups of juice. 
    - Add the juice and agave nectar to a blender, blend until integrated, and bottle. 
    - Store in the refrigerator for up to 2 weeks.
  - name: Sandalwood Tincture
    notes: Makes 8 ounces.
    ingredients: 
    - 6 drops sandalwood oil
    - 8 oz Polmos Spirytus Rektyfikowany
    steps:
    - In a blender, combine the sandalwood oil and Spirytus and blend for 30 seconds on high speed. 
    - Store in an airtight jar in a cool dry place indefinitely.
  - name: Ginger Syrup
    notes: Makes 6 ounces.
    ingredients: 
    - About five 1-inch cubes fresh ginger
    - 1 cup superfine sugar
    steps:
    - In a juice extractor, juice the ginger to yield 4 ounces (do not worry about peeling the ginger). 
    - Combine the juice and sugar in a saucepan over low heat; stir until the sugar is dissolved. 
    - Remove from the heat immediately, allow to cool, and then bottle. 
    - Store in the refrigerator for up to 4 weeks.
  - name: Kola Syrup
    notes: Makes 1 quart.
    ingredients: 
    - 3 cups white sugar
    - 2 tsp dark brown sugar
    - 2 cups water
    - 1 vanilla bean, sliced open
    - 2 star anise (crunched up)
    - 1 tsp juniper berries
    - 1 tsp coarsely smashed (not pulverized) cinnamon bark
    - 3 tsp minced ginger
    - 2 whole smashed (not pulverized) nutmeg
    - Zest of 1 lemon
    - Zest of 1 lime
    - Zest of 1 orange
    - 8 oz lime juice
    - 6 tsp kola extract (Grind kola nuts to obtain 4 Tbsp of the powder. Add this to 7 oz Polmos Spirytus Rektyfikowany and allow to sit for 20 minutes. Strain through a coffee filter into an airtight container. Lasts indefinitely.)
    - 4 tsp mate extract (Add 1 cup of mate loose-leaf tea to 7 oz Polmos Spirytus Rektyfikowany and allow to sit for 20 minutes. Strain through a coffee filter into an airtight container. Lasts indefinitely.)
    - 1 oz Angostura Aromatic Bitters
    - 2 tsp phosphoric acid
    - 1½ tsp molasses
    steps:
    - Add both sugars, the water, vanilla bean, star anise, juniper berries, cinnamon bark, ginger, nutmeg, and all the zests to a pot and bring to a simmer over medium heat; cook for 10 minutes. Allow to cool overnight (about 10 hours). Run through a chinois strainer and add the lime juice, kola extract, mate extract, Angostura bitters, phosphoric acid, and molasses and stir. Transfer to an airtight container. Store in the refrigerator for up to 1 month.
  - name: Coconut-Infused Clément Rhum Canne Bleue
    notes: Makes 750 mL.
    ingredients: 
    - 2 Tbsp coconut oil
    - 750 ml Clément Rhum Canne Bleue
    steps:
    - Add the coconut oil and rhum to a food-safe container. 
    - Whisk together to integrate and let sit in open air for 4 hours. 
    - Cover and place in the freezer overnight (about 10 hours). 
    - The next day, strain off the frozen solidified oil through a cheesecloth. 
    - Store in the refrigerator indefinitely.
  - name: Tea-Infused Singani 63
    notes: Makes 750 mL.
    ingredients: 
    - 4 Tbsp gunpowder green tea
    - 750 ml Singani 63
    steps:
    - In a food-safe container, mix together the green tea and the singani. 
    - Allow to infuse for 20 minutes, run through a chinois strainer, and bottle. 
    - Stored refrigerated indefinitely.
  - name: Yerba Mate-Infused BarSol Italia Selecto Peruvian Pisco
    notes: Makes 750 mL.
    ingredients: 
    - 3 Tbsp yerba mate
    - 750 ml pisco
    steps:
    - Combine the yerba mate with the pisco in a food-safe container and let sit for 8 minutes. 
    - Fine-strain through a coffee filter and rebottle. 
    - Store in the refrigerator indefinitely.
  - name: Tepache
    notes: Makes 3 quarts.
    ingredients: 
    - Skins and leftover pulp from the juicing of 1 large pineapple, yielding about 1 qt
    - 1 cone piloncillo or panela sugar (You can use about 1 cup raw sugar if you can’t find panela)
    - 3 qt water
    - 1 tsp allspice berries
    - 1 tsp whole cloves
    - 5 cardamom pods
    steps:
    - Combine all the ingredients in a food-safe container and let sit unrefrigerated for 3 to 5 days, until fermented. 
    - As the mixture begins to ferment, tiny bubbles will form on the top and the taste will become slightly (not very!) vinegary. 
    - Pass through a chinois strainer and then bottle. 
    - Store in the refrigerator for up to 1 month.
  - name: Jalapeño Syrup
    notes: Makes 6 ounces.
    ingredients: 
    - 5 or 6 jalapeños
    - 2 oz agave nectar
    steps:
    - Juice the jalapeños in a juice extractor to yield about 4 oz juice. 
    - Add the agave nectar, whisk together to integrate, and bottle. 
    - Store in the refrigerator for up to 2 weeks.
  - name: Agave Syrup
    notes: Makes approximately 12 ounces.
    ingredients: 
    - 8 oz agave nectar
    - 4 oz water
    steps:
    - Combine the agave and water in a blender and blend until fully integrated.
    - Bottle.
  - name: Cane Syrup
    notes: Makes approximately 1½ cups.
    ingredients: 
    - 1 cup cane sugar
    - 4 oz water
    steps:
    - Combine the sugar and water in a saucepan and bring to a simmer over low heat. 
    - Stir until the sugar is fully dissolved and integrated. 
    - Remove from the heat, let cool, and bottle.
  - name: Cardamom Tincture
    notes: Makes approximately 750 mL (1 bottle) after straining
    ingredients: 
    - ½ cup ground cardamom pods
    - 750 ml Polmos Spirytus Rektyfikowany or other 190 proof everclear
    steps:
    - Combine the cardamom and Spirytus in a food-safe container. 
    - Allow to sit unrefrigerated for 24 hours. 
    - Strain and bottle.
  - name: Cinnamon Bark Syrup
    notes: Makes approximately 2 cups.
    ingredients: 
    - 10 g cinnamon bark (about 4 sticks, crushed)
    - 1 cup superfine sugar
    - 1 cup water
    steps:
    - Combine the cinnamon bark, sugar, and water in a saucepan and bring to a boil over medium heat, stirring so the sugar fully dissolves. 
    - Remove from the heat and let cool for 15 minutes. 
    - Run through a chinois strainer and then bottle.
  - name: Demerara Syrup
    notes: Makes approximately 1½ cups.
    ingredients: 
    - 1 cup Demerara sugar
    - 4 oz water
    steps:
    - Combine the sugar and water in a saucepan and bring to a simmer over low heat. 
    - Stir until the sugar is fully dissolved and integrated. 
    - Remove from the heat, let cool, and bottle.
  - name: Honey Syrup
    notes: Makes approximately 12 ounces.
    ingredients: 
    - 8 oz honey
    - 4 oz water
    steps:
    - Combine the honey and water in a blender and blend until fully integrated. 
    - Bottle.
  - name: House Aromatic Bitters
    notes: Makes approximately 2 ounces.
    ingredients: 
    - 1 oz Bitter Truth Aromatic Bitters
    - 1 oz Fee Brothers Old Fashion Aromatic Bitters
    steps:
    - Combine both bitters in a bowl and blend together. 
    - Rebottle.
  - name: House Orange Bitters
    notes: Makes approximately 4 ounces.
    ingredients: 
    - 3 oz Regan’s Orange Bitters
    - 1 oz Angostura Orange Bitters
    steps:
    - Combine both bitters in a bowl and blend together. 
    - Rebottle.
  - name: Jalapeño-Infused Tequila
    notes: Makes approximately 750 mL. The recipe for the jalapeño tequila will vary because not all jalapeños are equally spicy. You need to taste it frequently to make sure it’s right. Ensure your tequila is not cold, as cold tequila will not infuse properly.
    ingredients: 
    - 4 jalapeños
    - 750 ml blanco tequila (I prefer tequila from the Tequila valley, such as Siembra Valles, Fortaleza, Arette, etc.)
    steps:
    - Remove the stems from the jalapeños. 
    - Cut the jalapeños in half and scrape the core (seeds and membranes) of two into a food-safe container. 
    - Dice the remaining jalapeños and place into the food-safe container. 
    - Add the tequila and allow to infuse for 12 to 20 minutes, depending on spice level desired. 
    - Rebottle.
  - name: Pineapple Syrup
    notes: Makes approximately 2 quarts.
    ingredients: 
    - 1 pineapple, cut into 1-inch cubes to yield about 28 oz
    - 1 qt superfine sugar
    steps:
    - Combine the pineapple and sugar in a bowl and place in refrigerator to macerate for 4 hours. 
    - Blend with an immersion blender and then strain through a colander and then through a chinois into 2-quart jar.
  - name: Saline Tincture
    notes: Makes approximately 2 ounces.
    ingredients: 
    - 1 Tbsp salt
    - 2 oz water
    steps:
    - Combine the salt and water in a saucepan and bring to a simmer over low heat. 
    - Stir until the salt is fully dissolved and integrated. 
    - Remove from the heat, let cool, and bottle.
  - name: Simple Syrup
    notes: Makes approximately 2 cups.
    ingredients: 
    - 1 cup superfine sugar
    - 1 cup water
    steps:
    - Combine the sugar and water in a saucepan and bring to a simmer over low heat. 
    - Stir until the sugar is fully dissolved and integrated. 
    - Remove from the heat, let cool, and bottle.
  - name: Vanilla Syrup
    notes: Makes approximately 2 cups.
    ingredients: 
    - 1 vanilla bean
    - 1 cup superfine sugar
    - 1 cup water
    steps:
    - Cut the vanilla bean in half and scrape the seeds into a saucepan. 
    - Add the remaining pod and the sugar and water to the pan and bring to a simmer over low heat. 
    - Stir until the sugar is fully dissolved and integrated. 
    - Remove from the heat and let cool for 20 minutes. 
    - Pour through a chinois strainer and then bottle.