source: "Smuggler's Cove, Exotic Cocktails, Rum, and the Cult of Tiki"
hidden: true
recipes:

#
  - name: SC House Spiced Rum
    notes: Makes two 750 mL bottles.
    ingredients: 
    - 2 (750 ml) bottles blended aged rum
    - 1 (8-inch) vanilla bean (split lengthwise)
    - 1 (5 by 1½-inch) strip of orange peel (with as little white pith as possible)
    - 6 allspice berries
    - 1 (8-inch) cinnamon stick
    - 6 whole cloves
    - ¼ teaspoon freshly grated nutmeg
    - 10 whole black peppercorns
    - 2 slices fresh ginger (unpeeled), cut into quarter-size coins
    - ⅓ cup SC Demerara syrup, optional
    steps:
    - In a half-gallon glass jar, combine the rum, vanilla bean (scraped seeds and pod), orange peel strip (you may wish to expel the orange peel oil a little as you add it), allspice, cinnamon stick, cloves, nutmeg, peppercorns, and ginger; seal airtight. 
    - Let the sealed jar of rum rest in a dark room for 72 hours, stirring once daily. 
    - Line a wire-mesh strainer with cheesecloth and set over a large bowl. 
    - Strain the spiced rum through the cheesecloth into the bowl. 
    - Add the SC Demerara Syrup (if desired, adjusting amount as you like; your chosen base rum may be plenty sweet as is) and stir to blend. 
    - Transfer to bottles and seal well. 
    - The spiced rum will keep for several months at room temperature.
  - name: Sweet Cream
    notes: 
    ingredients: 
    - 1 cup SC demerara syrup
    - 6 ounces heavy whipping cream
    steps:
    - In a drink mixer, blend 6 ounces of heavy whipping cream with 1 ounce of SC Demerara syrup until slightly thickened but still pourable (a few seconds).
  - name: SC Hot Buttered Rum Batter
    notes: Makes about 4 cups (48 servings) batter. When possible, it is always best to use fresh spices, but if you don’t have a small pepper mill to grind the anise seeds, allspice, and black pepper, I would suggest buying ground versions.
    ingredients: 
    - 1 teaspoon freshly ground cinnamon
    - 1 teaspoon freshly ground nutmeg
    - 1 teaspoon freshly ground black pepper
    - ¾ teaspoon ground cloves
    - ½ teaspoon ground allspice
    - ½ teaspoon ground anise seed
    - 2 cups salted butter
    - 4 cups packed golden brown sugar
    - 2 tablespoons Brer Rabbit Mild Molasses
    - 1 teaspoon vanilla extract
    steps:
    - Note the expiration date of the butter.
    - Combine the cinnamon, nutmeg, black pepper, cloves, allspice, and anise seed in a small bowl and set aside. 
    - Melt the butter in a saucepan over low heat. 
    - Add the sugar and stir. 
    - Add the molasses and vanilla extract and stir. 
    - Finally, stir in the spice mixture. 
    - At first, as you stir to combine, the butter will form a separate layer. 
    - Continue to stir over low heat until all the ingredients combine, including the butter, about 15 minutes. 
    - Remove from the heat. 
    - Let cool slightly. 
    - While still warm and malleable, pour the batter into a storage container. 
    - Let cool completely, then seal airtight, and store in the refrigerator where it will keep until the expiration date of the butter used to make it; note that date before you start the
  - name: 2:1 Simple Syrup
    notes: "Makes 4 cups (32 ounces). This recipe easily scales up to make more. One helpful tip: when you’re making a 2:1 simple syrup, the liquid yield is equivalent to the amount of sugar. So, to create 40 ounces of simple syrup you would use 40 ounces (5 cups) of sugar to 20 ounces of water."
    ingredients: 
    - 2 cups water
    - 4 cups granulated sugar
    steps:
    - Bring the water to a boil in a saucepan over high heat. 
    - Add the sugar and stir with a whisk until the sugar is dissolved, about 1 minute (the water should become clear such that you can see the bottom of the pot). 
    - Immediately remove from the heat. 
    - Store in a lidded bottle or other sealed container in the refrigerator. 
    - The syrup will keep, if refrigerated, for several weeks.
  - name: SC Demerara Syrup
    notes: "Makes 4 cups (32 ounces). The recipe easily scales up to make more. One helpful tip: when you’re making this syrup, the liquid yield is equivalent to the amount of total sugar used. So, to create 8 cups (64 ounces) of syrup you would use 8 cups (64 ounces) of sugar (6 cups white sugar, 2 cups demerara) to 4 cups (32 ounces) of water."
    ingredients: 
    - 2 cups water
    - 1 cup demerara sugar
    - 3 cups granulated sugar
    steps:
    - Bring the water to a boil in a saucepan over high heat. 
    - Add the demerara sugar and stir vigorously with a whisk (or use an immersion blender) until the sugar is dissolved, about 1 minute (the water should become clear such that you can see the bottom of the pot). 
    - Add the granulated sugar and stir vigorously until dissolved, about 1 minute. 
    - Immediately remove from the heat and let cool. 
    - Store in a lidded bottle or other sealed container in the refrigerator. 
    - The syrup will keep, refrigerated, for several weeks.
  - name: SC Honey Syrup
    notes: "Makes 3 cups (24 ounces). This is an equal parts honey-to-water recipe. One handy tip: After you pour the honey from its container into the saucepan and start to heat it, add water to the empty honey container until one-quarter full. Seal the container and shake vigorously to remove all of the honey clinging to the sides of the container. Then fill the rest of the container with water, and add the liquid to the saucepan when the honey is ready. For a richer honey flavor in your cocktails, you may wish to try 2 parts honey to 1 part water (3 cups of honey to 1½ cups of water) and experiment with different varieties of honey to find your favorite."
    ingredients: 
    - 1½ cups honey
    - 1½ cups water
    steps:
    - Heat the honey in a saucepan over medium heat until runny and not viscous—nearly to a boil but not quite. Add the water to the hot honey and whisk together. Immediately remove from the heat. Let cool. Store in a lidded bottle or other sealable container in the refrigerator. The syrup will keep, refrigerated, for several weeks.
  - name: SC Passion Fruit Syrup
    notes: Makes 3 cups (24 ounces). Increase the amount of puree for a tarter syrup.
    ingredients: 
    - 1½ cups Funkin passion fruit puree
    - 1½ cups 2:1 Simple Syrup, cooled
    steps:
    - In a bowl, whisk together the fruit puree and the syrup. Pour into a lidded bottle or other sealable container and store in the refrigerator. The syrup will keep, refrigerated, for up to 10 days.
  - name: SC Passion Fruit Honey
    notes: Makes 3 cups (24 ounces).
    ingredients: 
    - 1½ cups honey
    - 1½ cups Funkin passion fruit puree
    steps:
    - Heat the honey in a saucepan over medium heat until runny and not viscous—nearly to a boil but not quite. Remove from the heat and whisk in the passion fruit puree. Let cool. Pour into a lidded bottle or other sealable container and store in the refrigerator. The syrup will keep, refrigerated, for up to 10 days.
  - name: SC Mai Tai Rich Simple Syrup
    notes: Makes 4 cups (32 ounces).
    ingredients: 
    - 2 cups water
    - 4 cups demerara sugar
    - ½ teaspoon vanilla extract
    - ¼ teaspoon salt
    steps:
    - Bring the water to a boil in a saucepan over high heat. 
    - Add the demerara sugar and stir vigorously with a whisk (or use an immersion blender) until the sugar is dissolved, about 1 minute (the water should become clear such that you can see the bottom of the pot). 
    - Immediately remove from heat and let cool. 
    - Add the vanilla extract and salt and stir to combine. 
    - Pour into a lidded bottle or other sealable container and store in the refrigerator. 
    - The syrup will keep, refrigerated, for several weeks.
  - name: SC Vanilla Syrup
    notes: Makes 4 cups (32 ounces).
    ingredients: 
    - 2 cups water
    - 4 cups granulated sugar
    - 2 (8-inch) vanilla beans
    steps:
    - Bring the water to a boil in a saucepan over high heat. 
    - Add the sugar and stir with a whisk until dissolved, about 1 minute (the water should become clear such that you can see the bottom of the pot). 
    - Immediately remove from the heat. 
    - Halve the vanilla bean pods lengthwise and scrape the seeds into the syrup. 
    - Cut the scraped pods into thirds and add to the syrup.
    - Stir well. 
    - Cover and let sit at room temperature for 12 hours. 
    - Strain through cheesecloth into a bowl and then pour through a funnel into a lidded bottle or other sealable container. 
    - The syrup will keep, refrigerated, for several weeks.
  - name: SC Cinnamon Syrup
    notes: Makes 4 cups (32 ounces). We use cassia in our cinnamon syrup, but you can try the milder, sweeter ceylon cinnamon to add a different note.
    ingredients: 
    - 2 cups water
    - 3 (6-inch) cinnamon sticks, halved
    - 4 cups granulated sugar
    steps:
    - Put the water in a saucepan. 
    - Add the pieces of cinnamon stick to the water and bring to a boil over high heat. 
    - Add the sugar and stir with a whisk (or an immersion blender) until dissolved, about 1 minute (the liquid should become clear such that you can see the bottom of the pot). 
    - Immediately remove from the heat. 
    - Cover and let sit at room temperature for 12 hours. 
    - Strain through cheesecloth into a bowl and then use a funnel to pour into a lidded bottle or other sealable container. 
    - The syrup will keep, refrigerated, for several weeks.
  - name: SC Molasses Syrup
    notes: Makes 4½ cups (36 ounces). For a richer molasses flavor, increase the molasses-to-sugar ratio.
    ingredients: 
    - 2 cups water
    - 4 cups granulated sugar
    - 4 ounces Brer Rabbit Mild molasses
    steps:
    - Bring the water to a boil in a large saucepan. 
    - Add the sugar and stir with a whisk (or use an immersion blender) until dissolved, about 1 minute (the water should become clear such that you can see the bottom of the pot). 
    - Stir in the molasses. 
    - Immediately remove from heat and let cool. 
    - Pour into a lidded bottle or other sealable container and store in the refrigerator. 
    - The syrup will keep, refrigerated, for several weeks.
  - name: SC Grenadine
    notes: Makes 3 cups (24 ounces).
    ingredients: 
    - 2 cups POM Wonderful 100 Percent Pomegranate juice
    - 2 cups granulated sugar
    steps:
    - Add the pomegranate juice to a nonreactive saucepan. 
    - Bring the juice to a boil over high heat. 
    - Add the sugar and stir with a wooden spoon (or use an immersion blender) until dissolved, about 1 minute. 
    - Remove from heat and let cool. 
    - Pour into a lidded bottle or other sealable container and store in the refrigerator. 
    - The syrup will keep, refrigerated, for several weeks.
  - name: SC Coconut Cream
    notes: Makes about 3½ cups (27 ounces)
    ingredients: 
    - 1 (13½-ounce) can Thai Kitchen or other unsweetened coconut milk
    - ¼ teapoon salt
    - 13½ ounces 2:1 Simple Syrup
    steps:
    - In the can, the coconut milk will be partly solidified, with some liquid at the bottom. 
    - Use a spatula to gently scrape the contents of the can into a mixing bowl. 
    - Add the salt. 
    - Use an immersion blender or an electric hand mixer to combine the solids and liquid. 
    - Add the simple syrup to the mixing bowl (equal parts—use the empty coconut milk can to measure the simple syrup). 
    - Blend the ingredients with an immersion blender or electric hand mixer until well combined. 
    - Pour into a lidded bottle or other sealable container and store in the refrigerator. 
    - The coconut cream will keep, refrigerated, for 2 weeks.
  - name: SC Jerk Syrup
    notes: Makes 2 cups (16 ounces).
    ingredients: 
    - 1 cup water
    - 2 cups granulated sugar
    - 2 teaspoons SC Jerk Seasoning
    steps:
    - Bring the water to a boil in a saucepan over high heat. 
    - Add the sugar and seasoning and stir with a wooden spoon (or immersion blender) until dissolved, about 1 minute (the water should become clear such that you can see the bottom of the pot). 
    - Immediately remove from the heat. 
    - Let cool. Strain through cheesecloth into a bowl. 
    - Use a funnel to pour into a lidded bottle or other sealable container and store in the refrigerator. 
    - The syrup will keep, refrigerated, for several weeks.
  - name: SC Jerk Seasoning
    notes: Makes about 2 tablespoons.
    ingredients: 
    - 1¾ teaspoon ground dried thyme
    - 1 teaspoon freshly ground allspice berries
    - 1 teaspoon freshly ground black pepper
    - ½ teaspoon freshly ground cinnamon
    - ¼ teaspoon freshly ground nutmeg
    - 1 teaspoon cayenne pepper
    - ¼ teaspoon salt
    steps:
    - Add all the ingredients to a bowl, and mix together until well combined. 
    - Store any extra in a ziplock bag or other sealable container for future use.
  - name: SC Orgeat
    notes: Makes 5 to 6 cups (40 to 48 ounces).
    ingredients: 
    - 1 pound blanched almonds (3½ to 4 cups)
    - 4 cups water
    - 5 cups white granulated sugar (depends on yield of almonds; see method)
    - ¼ teaspoon rose water
    - ¼ teaspoon orange flower water
    - 2 teaspoons column still lightly aged rum (adds shelf life)
    steps:
    - Add the almonds and water to a large pot and bring to a boil over high heat. 
    - Strain almonds and set aside in a large bowl, while also reserving the remaining “almond water” in a separate bowl.
    - In a food processor fitted with the steel blade, grind 2 cups of the boiled almonds into small, rice-size pieces, about 10 seconds. 
    - Slowly add about 11 ounces of the “almond water” to the food processor and blend until the water and almonds combine to an “almond paste,” about 10 seconds. 
    - This “paste” will be the consistency of Cream of Wheat or watery oatmeal.
    - Pour contents into a gallon pitcher. Repeat with the remaining almonds and “almond water,” and add this second  batch of “almond paste” to the first batch.
    - Let the almond paste cool for about 1 hour. 
    - Set a fine-mesh wire strainer lined with cheesecloth over a 4-quart pot. 
    - In batches, ladle some of the “almond paste” into a square of cheesecloth in your hand and squeeze out the liquid (“almond milk”) from the paste over the cheesecloth-lined strainer and into the pot. 
    - Discard the dry almond remains. Repeat until all paste has been strained. 
    - At the end, you may want to also squeeze the cheesecloth that lined the strainer to get the last of any remaining liquid.
    - Set a fine-mesh wire strainer lined with cheesecloth over a 4-cup glass measuring cup. 
    - Pour the almond milk through the cheesecloth-lined strainer into the measuring cup and make note of the yield (you should have about 2½ cups of almond milk). 
    - Set a fine-mesh strainer lined with cheesecloth over a clean 4-quart pot and pour the almond milk through the cheesecloth-lined strainer into the pot.
    - Measure twice as much sugar as the almond milk yield (about 5 cups) and add to the pot of almond milk. 
    - Stir with a whisk over low heat until the sugar is fully incorporated into the milk, creating a thick syrup, about 15 minutes. 
    - Taste it—it is ready when there is no grittiness. 
    - Remove the pot from the heat. 
    - When the syrup begins to cool add the rose and orange flower waters and the rum. 
    - Stir periodically as it cools. 
    - It may separate so a thick skin forms on the surface. 
    - Stir vigorously to reincorporate the skin as best as possible into the rest of syrup. 
    - Once completely cool, stir vigorously and then strain through a metal-screened or cheesecloth-lined funnel (to remove any residual undissolved matter) into a sealable storage container. 
    - The orgeat will keep, refrigerated, for several weeks.
  - name: SC Hibiscus Liqueur
    notes: Makes 4 cups (32 ounces).
    ingredients: 
    - ½ cup honey
    - 2½ cups SC Spiced Hibiscus Infusion
    - 1 cup 2:1 Simple Syrup
    steps:
    - In a microwave, heat the honey in a microwave-safe bowl until runny, about 40 seconds (or, heat in a saucepan on the stovetop for approximately 3 minutes over medium heat). 
    - Add the infusion and syrup and stir to thoroughly blend. 
    - Transfer to bottles and seal well. 
    - The liqueur will keep refrigerated for several weeks.
  - name: SC Spiced Hibiscus Infusion
    notes: Makes about 4 cups (32 ounces).
    ingredients: 
    - 3 quarter-size discs of unpeeled fresh ginger
    - 10 whole cloves
    - 1 liter blended lightly aged rum
    - ¾ cup dried hibiscus flowers
    steps:
    - In a large glass jar with a lid, combine the ginger, cloves, and rum and let sit, covered at room temperature, for 24 hours. 
    - Strain out the cloves and ginger from the rum and discard. 
    - Add the dried hibiscus flowers to the rum. 
    - Let sit, covered at room temperature, for 48 hours. 
    - Strain the dried flowers from the rum and discard. 
    - Transfer the infused rum to glass bottles and seal well. 
    - The infusion will keep at room temperature on your shelf for at least 6 months.
  - name: SC Hellfire Tincture
    notes: Makes about 2 cups (16 ounces). WARNING! When you are making this, you are essentially creating pepper spray in the air. Wear a dust mask and open the windows to your kitchen.
    ingredients: 
    - 4 cups mixed fresh hot chiles (such as habanero, Fresno, red jalapeño, and so on), coarsely chopped, stems and seeds included
    - 1 cup dry white wine
    - 2 cups brandy
    steps:
    - In a large saucepan over medium heat, cook the chopped peppers with the wine until the peppers are soft and the wine has been absorbed or evaporated. 
    - Remove from the heat. 
    - Let the peppers cool. 
    - Put them in a sealable glass jar with the brandy, seal well, and let sit at room temperature for two weeks. 
    - Strain through cheesecloth into a large container, then transfer to sealable bottles. 
    - The tincture will keep at room temperature for at least a year.
  - name: Li Hing Mui Syrup
    notes: Makes about 2 cups (16 ounces).
    ingredients: 
    - 2 teaspoons li hing mui powder
    - 2 cups granulated sugar
    - 1 cup water
    steps:
    - Stir the li hing mui powder into the sugar in a bowl. 
    - Bring the water to a boil in a saucepan over high heat. 
    - Add the li hing mui–sugar mixture and stir until dissolved, about 1 minute (the liquid should become clear such that you can see the bottom of the pot). 
    - Remove from the heat and let cool. 
    - Store in a lidded bottle or sealable container in the refrigerator for several weeks.
  - name: Croutons for Flaming Bowls
    notes: Makes about 150 (3/4 inch-square) croutons.
    ingredients: 
    - 1 loaf thin-crusted white bread, crusts trimmed and bread cut into ¾-inch cubes
    steps:
    - Preheat the oven to 200°F. 
    - Put the cubes in a single layer on a baking sheet. 
    - Heat until they are dry and crisp, 45 minutes to 1 hour. 
    - Let cool completely on the baking sheet, then store in an airtight plastic container. 
    - They will keep for several weeks.