source: "Sherry: A Modern Guide to the Wine World’s Best-Kept Secret"
hidden: true
recipes:

#Artist's Special
  - name: Redcurrant Syrup
    notes: 
    ingredients: 
    - 1 cup stemmed redcurrants
    - ¼ cup raspberries
    - 1¼ cups sugar
    - 7 ounces boiling water
    steps:
    - In a bowl, combine the currants and raspberries and muddle. 
    - Cover with a cloth or kitchen towel and let stand at room temperature overnight. 
    - Add the sugar and boiling water and stir to combine. 
    - Let cool, and finely strain into a jar or glass bottle. 
    - Refrigerate for up to 1 month.
#Daniel Webster's Punch
  - name: Ice Ring
    notes: 
    ingredients: 
    - 5 strawberries, cut in half lengthwise
    - 5 slices of pineapple
    - 10 mint leaves
    steps:
    - To a bundt cake mold, add enough water to fill halfway to the top. 
    - Evenly place the strawberries, pineapple, and mint. 
    - Freeze overnight.
#Pale Rider
  - name: Jalapeño Tequila
    notes: 
    ingredients: 
    - 2 fresh jalapeños
    - 1½ cups silver tequila
    steps:
    - Cut the jalapeños lengthwise and extract the seeds and membranes; add them to a glass bowl. 
    - Discard the rest of the pepper. 
    - Add the tequila to the seeds and membranes and infuse for 10 to 20 minutes, depending on the heat of the peppers. 
    - Finely strain and bottle. 
    - Keep at room temperature for up to 1 month.
#Coffey Park Swizzle
  - name: Ginger Syrup
    notes: 
    ingredients: 
    - ½ cup fresh-pressed ginger juice
    - ¾ cup sugar
    steps:
    - Combine the ginger juice and sugar in a small saucepan and heat over low. 
    - Stir continuously until the mixture heats through and the sugar dissolves, about 7 to 10 minutes. 
    - Remove from the heat and set aside to cool. 
    - Transfer to a glass container and store covered in the refrigerator for up to 1 month.
#Mariah Sherry
  - name: Grapefruit Shrub
    notes: Keeps for up to 4 months.
    ingredients: 
    - 2 ruby red grapefruits
    - 1¾ cups cane sugar
    - 1¾ cups ruby red grapefruit juice
    - ¾ cup apple cider vinegar
    - ½ ounce red peppercorns, crushed
    steps:
    - Peel the grapefruits, avoiding as much of the bitter white pith as possible, and transfer them to a glass mixing bowl. 
    - Add the sugar and muddle, then cover and let sit overnight at room temperature. 
    - Add the grapefruit juice, taste, and adjust the seasoning, adding more sugar if necessary. 
    - Add the vinegar, about ¼ cup at a time, until the taste is to your liking. 
    - Finely strain the mixture and pour into a glass container, then add the peppercorns and refrigerate overnight. 
    - The following day, strain the liquid through a cheesecloth and discard the peppercorns. 
    - Stored covered in the refrigerator.
#I Am... I Said
  - name: Menthol Tincture
    notes: 
    ingredients: 
    - 1 ounce menthol crystals
    - 5 ounces vodka
    steps:
    - Combine the menthol crystals and vodka in a small jar. 
    - Cap the jar and shake. 
    - The crystals will dissolve and infuse after about a day. 
    - It keeps, according to Schick, “probably forever.”
#Sherry Bloody Mary
  - name: Bloody Mary Mix
    notes: You’ll have enough mix for 4 drinks. Keeps for 3 days in the refrigerator.
    ingredients: 
    - 2 cups tomato juice
    - 1 teaspoon hot paprika
    - 2 teaspoons sherry vinegar
    - 2 teaspoons Worcestershire sauce
    - ¼ teaspoon cracked pepper
    - ¼ teaspoon salt
    - 2 pinches of cayenne, or to taste
    - ¼ teaspoon celery salt
    steps:
    - Combine all the ingredients and store, covered in the refrigerator, for up to 3 days.