source: "The Negroni: Drinking to La Dolce Vita"
hidden: true
recipes:


#White Negroni With Campari Caviar
  - name: Campari Caviar
    author: 
    notes: 
    ingredients:
    - 18 ounces water
    - 2 ounces Campari
    - 2 ounces Combier Crème de Pamplemousse Rosé Liqueur 
    - 1 ounce Luxardo Maraschino Liqueur
    - 1.5 grams sodium alginate
    - 5 grams calcium lactate
    steps:
    - Combine 3 ounces of the water, the Campari, the Crème de Pamplemousse liqueur, the maraschino liqueur, and the sodium alginate. In a separate large bowl, combine the remaining 15 ounces of water with the calcium lactate to form a bath. Use a dropper to slowly drop the Campari mixture into the bath. Let the Campari droplets set for about 30 seconds (the longer they set, the firmer they will become). Remove the caviar from the bath with a strainer and rinse under cold water.

#Minimo di Negroni
  - name: Plymouth Gin Infused With Saffron
    author: 
    notes: 
    ingredients:
    - 1 (750 ml) bottle Plymouth gin
    - 2 grams (about 4 teaspoons) whole saffron threads
    steps:
    - Combine the gin and saffron in a jar with a tight-fitting lid. Seal the jar and shake gently. Let infuse for about 8 hours or overnight. Strain through a double layer of dampened cheesecloth.

#Lemon Balm Negroni
  - name: Tanqueray London Dry gin Infused With Lemon Balm
    author: 
    notes: 
    ingredients:
    - 1 (750 ml) bottle Tanqueray London Dry gin
    - 1 cup fresh lemon balm
    steps:
    - Combine the gin and lemon balm in a jar with a tight-fitting lid. Seal the jar and shake gently. Let infuse for about 8 hours or overnight. Strain through a double layer of dampened cheesecloth.
    tags:

#Negroni Fizz
  - name: Rosemary Simple Syrup
    author: 
    notes: 
    ingredients:
    - ½ cup water
    - ½ cup sugar
    - 5 rosemary sprigs
    steps:
    - Combine the ingredients in a small saucepan over medium-high heat. Bring to a boil, turn the heat down to allow the mixture to simmer, and cook, stirring frequently, until the sugar dissolves, about 5 minutes. Remove from the heat and allow to cool completely, then strain through a double layer of cheesecloth.
    tags:

#Dog and Pony
  - name: Chocolate Porter Reduction
    author: 
    notes: 
    ingredients:
    - 5 tablespoons superfine sugar
    - 12 ounces chocolate porter
    steps:
    - Combine the sugar and porter in a medium saucepan over medium heat. (Jill uses chocolate porter from London’s Meantime Brewing Company.) Bring to a simmer, then lower the heat and simmer gently for 5 minutes. Let cool before using.
    tags:

#Street & Smith
  - name: Campari Infused With Grapefruit Peel
    author: 
    notes: 
    ingredients:
    - 1 large grapefruit
    - 1 (750 mL) bottle Campari
    steps:
    - Use a fine grater to remove the zest from the grapefruit. Combine the zest and Campari in a jar with a tight-fitting lid. Seal the jar and shake gently. Let infuse for about 24 hours. Strain through a double layer of dampened cheesecloth. Store in the refrigerator.
    tags:

#My Fave!
  - name: Bulleit Bourbon Infused With Skillet-Roasted Figs and Pears
    author: 
    notes: 
    ingredients:
    - 2 anjou pears, quartered
    - 8 figs, halved
    - 5 ounces water
    - 1 liter Bulleit Bourbon
    steps:
    - Preheat the oven to 350° Fahrenheit. Heat a dry cast-iron skillet over high heat until very hot. Put the pears and the figs in the skillet and stir until the figs begin to blister. Pour the water over the fruit, stir, and then transfer the skillet to the oven. Bake for 12 minutes.
    - Transfer the contents of the skillet to a sturdy heatproof jar, pour in the bourbon, and seal the jar. Shake the jar gently once or twice a day for 2 days. Strain through a double layer of dampened cheesecloth.
    tags:

#Pepper Negroni
  - name: Yellow Chartreuse Infused With Serranos
    author: 
    notes: 
    ingredients:
    - 3 serrano chiles, split lengthwise
    - 1 (750mL) bottle Yellow Chartreuse
    steps:
    - Combine the serranos and Chartreuse in a jar with a tight-fitting lid. Seal the jar and shake gently. Let infuse for about 24 hours. Strain through a double layer of dampened cheesecloth.
    tags:

#Pizza Negroni
  - name: Aviation Gin Infused With Mozzarella and Parmesan
    author: 
    notes: 
    ingredients:
    - 4 ounces mozzarella cheese, roughly chopped
    - 2 ounces rind from Parmesan cheese, roughly chopped
    - 1 (750 mL) bottle Aviation gin
    steps:
    - Combine the mozzarella, parmesan, and gin in a jar with a tight-fitting lid. Seal the jar and shake gently. Let infuse for 5 to 7 days. Discard the solids, then freeze for 24 hours. Strain once more through a coffee filter to remove any solidified fat.
    tags:
  - name: Tomato Water
    author: 
    notes: Makes a little less than 2 cups.
    ingredients:
    - 1½ pounds ripe tomatoes
    - Large pinch of salt
    steps:
    - Line a sieve with cheesecloth and set it over a large bowl. Coarsely chop the tomatoes, then place in the lined sieve and sprinkle with salt. Cover and chill for at least 12 hours, then discard the solids and use the tomato water as directed.
    tags:

#Negroni de Provence
  - name: Citadelle Gin Infused With Lavender
    author: 
    notes: 
    ingredients:
    - 3 ounces Lavender
    - 1 (750 mL) bottle Citadelle gin
    steps:
    - Combine the lavender and gin in a jar with a tight-fitting lid. Seal the jar and shake gently. Let infuse for about 8 hours or overnight. Strain through a double layer of dampened cheesecloth.
    tags:
  - name: Lillet Blanc Infused With Herbes de Provence
    author: 
    notes: 
    ingredients:
    - ½ cup herbes de provence
    - 1 (750 mL) bottle Lillet Blanc
    steps:
    - Combine the herbes de Provence and Lillet in a jar with a tight-fitting lid. Seal the jar and shake gently. Let infuse overnight. Strain through a double layer of dampened cheesecloth.
    tags:

#Stiletta
  - name: Campari Infused With Star Anise
    author: 
    notes: 
    ingredients:
    - 20 star anise pods
    - 1 (750 mL) bottle Campari
    steps:
    - Combine the star anise and Campari in a jar with a tight-fitting lid. Seal the jar and shake gently. Let infuse for about 8 hours or overnight. Strain through a double layer of dampened cheesecloth.
    tags:

#Negronio Cheesecake
  - name: Vermouth Reduction
    author: 
    notes: 
    ingredients:
    - 1 scant cup demerara sugar
    - 1 (750 mL) bottle sweet vermouth
    steps:
    - Combine the sugar and vermouth in a heavy, nonreactive saucepan over medium-high heat. Cook, stirring constantly, until the sugar is dissolved and the mixture begins to simmer. Lower the heat to medium and cook, stirring frequently, until reduced by about half (to approximately 1½ cups), about 15 to 20 minutes. Let cool before using.
    tags:

#Negroni Caramel Popcorn
  - name: Gin Salt
    author: 
    notes: 
    ingredients:
    - 1 teaspoon juniper berries
    - ¾ teaspoon coriander seeds
    - ½ teaspoon cardamom seeds
    - ¼ teaspoon fennel seeds
    - 1 teaspoon anise seeds
    - Scant ¼ teaspoon white peppercorns
    - ½ star anise pod
    - ¼ teaspoon ground dry ginger
    - 1½ teaspoons dried mandarin orange peel
    - 2 tablespoons plus ½ teaspoon fine sea salt
    steps:
    - Combine everything except the salt in a blender, spice grinder, or clean coffee mill and process until very fine. Pass through a fine-mesh sieve to remove any larger pieces. Mix with the salt.
    tags: