source: Imbibe
hidden: true
recipes:

# Bala de Canon
  - name: Cantaloupe Purée
    notes: |+2
      
    ingredients: 
    - Ripe cantaloupe
    steps:
    - Skin a ripe cantaloupe and cut the fruit into chunks, reserving the seeds and pulp. Purée in a blender (with the seeds, which add flavorful complexity) until smooth; press through a fine strainer to remove solids. Refrigerate and use within 2 days.
#Cantaloupe Paloma
  - name: Jasmine-Infused Agave Syrup
    notes: |+2
      
    ingredients: 
    - 4 grams jasmine pearls
    - 8 oz. water
    - agave nectar
    steps:
    - Make 1 cup of jasmine tea using 4 grams of jasmine pearls and 8 oz. or 240 mL of water. Strain and add twice the amount of agave nectar by weight (8 oz. agave nectar to 4 oz. jasmine tea). The agave will keep in the refrigerator for at least 3 months.