source: "The Negroni: Drinking to La Dolce Vita"
hidden: true
recipes:


#The Edible Negronis
  - name: Negroni Popsicle
    author: Jake Godby
    notes: What could be more refreshing than walking around on a hot summer’s day with one of these to keep your mouth watering, huh? Makes about 12 popdicles, depending on the size of your mold.
    ingredients:
    - 1 cup water
    - ½ cup sugar
    - ¼ cup gin
    - ¼ cup sweet vermouth
    - ¼ cup Campari
    - 2½ cups fresh pink grapefruit juice
    - Pinch of salt
    steps:
    - Combine the water and sugar in a heavy saucepan and bring to a boil over medium-high heat. Remove from the heat and stir in the remaining ingredients. Let cool to room temperature, then pour into ice-pop molds and freeze according to the manufacturer’s instructions.
    tags:
      - the edible negronis
  - name: Negroni Cheesecake
    author: Monica Berg
    notes: Monica created this recipe when she worked at Aqua Vitae in Oslo, Norway. I first met her a few years ago when visiting the good folk at G’Vine Gin in Cognac, France, where we had some damned good chin-wags and capped off the week with a drunken yoga session at around midnight. She now works at the Pollen Street Social in London, where she can keep a close eye on her beau, Alex Kratena of London’s Artesian bar. I think of them as the royal family of cocktailians in the UK. Back when Monica was still working in Oslo, she noted that the Negroni Cheesecake basically started out as a joke but became a tradition for birthdays and staff parties. Note that the raspberry-infused Campari for the topping must rest overnight, so plan accordingly. Makes 8 to 12 servings.
    ingredients:
    - 3½ ounces fresh raspberries
    - ⅔ cup Campari
    - 3 ounces raspberry gelatin mix
    - 8 ounces graham crackers, crumbled
    - 9 tablespoons butter, melted
    - 1 tablespoon plus 1 teaspoon Vermouth Reduction
    - 5 to 6 sheets gelatin
    - ⅔ cup fresh orange juice
    - 7 ounces cream cheese, at room temperature
    - 1 cup sour cream
    - 5 tablespoons powdered sugar, or more for a sweeter cheesecake
    - 2 ounces gin, preferably with strong juniper notes
    - 1 drop vanilla extract
    - 1½ cups whipping cream
    steps:
    - To make the topping, put the raspberries in a container with a lid. Pour in the Campari, cover, and refrigerate overnight.
    - Make the gelatin according to the package instructions, replacing a little less than half of the ice water with the Campari mixture. Chill until cold but not set.
    - To make the crust, combine the graham cracker crumbs, butter, and Vermouth Reduction in a bowl and mix well. Press the mixture into the bottom and up the sides of a 9- to 10-inch nonstick springform pan. Refrigerate the crust while you make the filling.
    - To make the filling, combine the gelatin sheets and orange juice in a large bowl and let sit until the gelatin is completely dissolved. Add the cream cheese and stir to combine. Add the sour cream, powdered sugar, gin, and vanilla extract and stir until thoroughly blended.
    - In a separate bowl, beat the whipping cream until soft peaks form. Gradually fold the whipped cream into the cream cheese mixture.
    - To assemble the cheesecake, pour the filling into the chilled crust and refrigerate until set, at least 3 hours. Pour the partially set gelatin mixture over the top and return to the refrigerator overnight.
    tags:
      - the edible negronis
  - name: Parson's Negroni Slushy
    author: Charlie Schott
    notes: Makes 2 or 3 servings. Charlie kindly adjusted Parson’s recipe for this slushy, figuring that you probably don’t have a slushy machine. The recipe here works well in a blender. Or, if you have an ice cream machine, add around 4½ ounces of water for the best results. The Luxardo Bitter, by the way, brings a nice ripe cherry note to the potion.
    ingredients:
    - 2 ounces Letherbee gin
    - 2 ounces sweet vermouth
    - 2 ounces Luxardo bitter
    - 2½ ounces fresh grapefruit juice
    - 2½ ounces fresh orange juice
    - 1½ cups crushed ice
    - "Garnish: frozen orange half wheels"
    steps:
    - Put all the ingredients in a blender and process at high speed, stopping occasionally to stir the ingredients together. Continue blending at high speed, adding more crushed ice to achieve the desired consistency. Serve garnished with the frozen orange half wheels.
    tags:
      - the edible negronis
  - name: Negroni Ice Cream
    author: Natasha Case & Freya Estreller
    notes: Makes about 6 servings. When making this ice cream, use the freshest eggs available for best results. If possible, refrigerate the base for a full 24 hours—the longer, the better. We like to chill our bases in plastic or stainless steel pitchers (with airtight lids) for easy pouring into the ice cream maker after chilling.
    ingredients:
    - 2 cups whole milk
    - 2 cups heavy cream
    - 1¼ cups granulated sugar
    - 8 large egg yolks
    - Zest of 1 orange
    - Juice of ½ orange
    - ⅔ ounce Aviation gin
    - ⅔ ounce vermouth, preferably Cinzano or Carpano
    - ⅔ ounce Campari
    - Pinch of salt
    steps:
    - In a large, heavy saucepan, combine the milk, cream, and half of the sugar. Cook over high heat, stirring occasionally, until the mixture comes to a boil, about 5 minutes.
    - Meanwhile, in a medium bowl, whisk the yolks and the remaining half of the sugar until smooth, heavy, and pale yellow, about 30 seconds.
    - When the cream mixture just comes to a boil, whisk, then remove from the heat. While whisking constantly, pour half of the cream mixture into the egg yolk mixture in a slow stream and continue whisking until thoroughly blended.
    - Return the pan to the stove top over low heat. While whisking constantly, slowly pour the cream mixture back into the pan. Switch to a wooden spoon, and cook, stirring constantly, until the mixture registers between 165° and 180° Fahrenheit on an instant-read thermometer, about 2 minutes. Do not heat above 180° Fahrenheit, or the egg yolks will set up. The mixture should be steaming but not boiling, and slightly thickened—enough to coat the back of a spoon. If you blow on the back of the spoon and the mixture ripples, you’ve got the right consistency.
    - Pour the mixture into a clean, airtight container. Cover and refrigerate for at least 12 hours and no longer than 5 days before using.
    - Add the orange zest and juice and stir until combined. Pour into an ice cream maker and process according to the manufacturer’s instructions until the ice cream takes on a consistency like soft-serve ice cream. Add the gin, vermouth, Campari, and salt and process for several more minutes, until the consistency is once again like soft-serve ice cream. (The alcohol will initially reverse the freezing process.)
    - Remove from the ice cream maker and store in a sealed container in the freezer for at least 2 hours before serving.
    tags:
      - the edible negronis
  - name: Negroni Caramel Popcorn
    author: Stephen Lee
    notes: Makes about 8 servings. Many thanks to Stephen for sending me this recipe for Perbacco’s spectacular Negroni popcorn.
    ingredients:
    - 8 cups popped popcorn
    - 1 cup granulated sugar
    - 2 tablespoons gin salt
    - 1 cup Campari
    - ½ cup sweet vermouth
    - ¼ cup water
    - 2 tablespoons unsalted butter
    - 2 tablespoons honey
    - 4 teaspoons corn syrup
    - 1 orange twist
    - ½ teaspoon baking soda
    steps:
    - Line a sheet pan with parchment paper. Oil the parchment paper and the sides of the baking sheet. Put the popcorn in a large bowl.
    - Combine the sugar, Gin Salt, Campari, vermouth, water, butter, honey, corn syrup, and orange twist in a heavy saucepan over medium heat. Cook, stirring frequently, until golden brown. Stir in the baking soda.
    - Drizzle the mixture over the popcorn and toss gently until evenly coated. Transfer to the prepared pan and spread in a thin layer, tossing until cool. Enjoy immediately, or store in an airtight container.
    tags:
      - the edible negronis